#pragma once

// GENERATED FILE -- do not hand-edit. Source: protocol.yaml. Regenerate with `python tools/gen_protocol.py`.

// The only two upstream CMD/RESP slots beebo claims -- every beebo
// action is a flat u8 sub-id carried as the first payload byte after
// one of these.
#define CMD_BEEBO        222
#define RESP_CODE_BEEBO  223

// beebo command sub-ids (payload byte 0 after CMD_BEEBO)
#define BEEBO_CMD_OTA_BEGIN                      128  // start OTA session
#define BEEBO_CMD_OTA_WRITE                      129  // write firmware chunk
#define BEEBO_CMD_OTA_END                        130  // finalize and reboot. payload (optional): 4B LE uint32 epoch seconds, the caller's own current clock -- if present, used for the deferred restart's NVS persistence and live clock correction instead of this device's own current time (see REBOOT_WITH_TIME's own desc for why); omit for the old behavior
#define BEEBO_CMD_SET_WIFI_CREDS                 131  // payload: ssid\0pwd\0 -- save to NodePrefs and apply live, no reboot (define WIFI_CREDS_REBOOT at build time for the old reboot-to-apply behavior)
#define BEEBO_CMD_GET_TRANSPORT_CONFIG           132  // reply OK + value (byte0=ble_enabled, byte1=tcp_enabled)
#define BEEBO_CMD_SET_TRANSPORT_CONFIG           133  // payload: [ble_enabled][tcp_enabled][usb_enabled][reboot]
#define BEEBO_CMD_GET_SAVE_PREFS                 134  // reply OK + value (byte0 = save_prefs, 1=on)
#define BEEBO_CMD_SET_SAVE_PREFS                 135  // payload: 1 byte -- 0=off, 1=on, 2=restore(reload), 3=commit(write now)
#define BEEBO_CMD_SET_CW                         136  // bench CW carrier. payload: [on:1][max_secs:2 LE]; on=0 stops
#define BEEBO_CMD_SET_TX_OPTIMIZE                137  // PA optimization. payload: [on:1]; 1=paOptTable(default), 0=fixed/monotonic
#define BEEBO_CMD_GET_NEIGHBORS                  138  // stream the direct (zero-hop) neighbour table
#define BEEBO_CMD_GET_MONRING                    139  // read monitor ring. payload: [after_seq:4 LE] (optional) [after_ts:4 LE] (optional, capture-time epoch of the record at after_seq as the client last recorded it -- lets the firmware detect a reboot/clear/wraparound since then and override to a full read, since after_seq alone can alias across MonRing::_next_seq resetting to 0; see the reply's reset flag)
#define BEEBO_CMD_SET_MONRING                    140  // control RX capture. payload: [op:1] 0=pause 1=resume 2=clear 3=set config (byte2, persisted)
#define BEEBO_CMD_SET_XFER_CAPS                  141  // (BULK_XFER): negotiate bulk-transfer caps. payload: [max_rx_frame:2 LE][flags:1]; flags bit0=accept streamed reads
#define BEEBO_CMD_GET_RADIO_FEM_RXGAIN           142  // read FEM RX gain
#define BEEBO_CMD_SET_RADIO_FEM_RXGAIN           143  // set FEM RX gain
#define BEEBO_CMD_GET_RADIO_RXGAIN               144  // read radio RX gain
#define BEEBO_CMD_SET_RADIO_RXGAIN               145  // set radio RX gain
#define BEEBO_CMD_APP_DISCONNECT                 146  // disconnect the companion session
#define BEEBO_CMD_GET_MONRING_CONFIG             147  // reply OK + value (byte0 = monring_config bitmask)
#define BEEBO_CMD_GET_WIFI_SSID                  148  // reply RESP wifi ssid + ssid bytes (no NUL, may be 0 bytes if unset)
#define BEEBO_CMD_GET_WIFI_PWD_SET               149  // reply OK + value (4B LE) = 1 if wifi_pwd is set, 0 if empty -- never the password itself
#define BEEBO_CMD_GET_ADC_MULTIPLIER             150  // reply OK + value (4B LE float) = battery ADC divider multiplier (0.0 = board default)
#define BEEBO_CMD_SET_ADC_MULTIPLIER             151  // payload: 4B LE float. 0.0 resets to board default
#define BEEBO_CMD_SEND_POKE                      152  // originate a 'poke' to a contact. payload: [pub_key:PUB_KEY_SIZE]
#define BEEBO_CMD_GET_BATT_STATE                 153  // reply OK + value (4B LE) = BATT_STATE_* (byte0)
#define BEEBO_CMD_GET_BATT_SAMPLE_PERIOD         154  // reply OK + value (4B LE) = seconds (0 = default)
#define BEEBO_CMD_SET_BATT_SAMPLE_PERIOD         155  // payload: 4B LE uint32 seconds; 0 resets to default; persisted
#define BEEBO_CMD_GET_BATT_PRESENT               156  // reply OK + value (1B) = 0 unknown/1 no/2 yes; user-declared, persisted
#define BEEBO_CMD_SET_BATT_PRESENT               157  // payload: 1B value (0/1/2); persisted
#define BEEBO_CMD_GET_ADC_RESOLUTION             158  // reply OK + value (1B) = ADC sample resolution, bits (10 or 12)
#define BEEBO_CMD_SET_ADC_RESOLUTION             159  // payload: 1B value (10 or 12); persisted
#define BEEBO_CMD_GET_QUIET                      160  // reply OK + value (1B) = bench-quiet state (0=off, 1=on)
#define BEEBO_CMD_SET_QUIET                      161  // payload: 1B value (0=off -> reboots, 1=on -> sleeps radio+FEM); RAM-only, not persisted
#define BEEBO_CMD_GET_BATT_SAMPLE_WINDOW         162  // reply OK + value (4B LE) = seconds (0 = default)
#define BEEBO_CMD_SET_BATT_SAMPLE_WINDOW         163  // payload: 4B LE uint32 seconds; 0 resets to default; persisted
#define BEEBO_CMD_GET_BATT_CHARGED_MV            164  // reply OK + value (4B LE) = mV (0 = default, see BATT_FULL_MV_DEFAULT)
#define BEEBO_CMD_SET_BATT_CHARGED_MV            165  // payload: 4B LE uint32 mV; 0 resets to default; persisted
#define BEEBO_CMD_SET_BATT_STATE                 166  // payload: 1B value = BATT_STATE_*; RAM-only, not persisted; re-seeds the trend anchor
#define BEEBO_CMD_GET_IDLE_MARGIN                167  // reply OK + value (4B LE) = ms (0 = default, see IDLE_MARGIN_DEFAULT_MS)
#define BEEBO_CMD_SET_IDLE_MARGIN                168  // payload: 4B LE uint32 ms; 0 resets to default; persisted
#define BEEBO_CMD_GET_NODE_ROLE                  169  // reply OK + value (4B LE) = NODE_ROLE_* (0=companion, 1=repeater); multi_role only
#define BEEBO_CMD_SET_NODE_ROLE                  170  // payload: 1B value = NODE_ROLE_*; persisted; hot switch (immediate); multi_role only
#define BEEBO_CMD_GET_REPEAT_MODE                171  // reply OK + value (1B) = 1 if repeater will forward packets, 0 if not (ComPrefs.disable_fwd inverted); multi_role only
#define BEEBO_CMD_SET_REPEAT_MODE                172  // payload: 1B value (0/1); writes ComPrefs.disable_fwd inverted; multi_role only
#define BEEBO_CMD_GET_TXDELAY_FACTOR             173  // reply OK + value (4B LE float) = ComPrefs.tx_delay_factor; multi_role only
#define BEEBO_CMD_SET_TXDELAY_FACTOR             174  // payload: 4B LE float; writes ComPrefs.tx_delay_factor; multi_role only
#define BEEBO_CMD_GET_DIRECT_TXDELAY_FACTOR      175  // reply OK + value (4B LE float) = ComPrefs.direct_tx_delay_factor; multi_role only
#define BEEBO_CMD_SET_DIRECT_TXDELAY_FACTOR      176  // payload: 4B LE float; writes ComPrefs.direct_tx_delay_factor; multi_role only
#define BEEBO_CMD_GET_ALLOW_READ_ONLY            177  // reply OK + value (1B) = ComPrefs.allow_read_only; multi_role only
#define BEEBO_CMD_SET_ALLOW_READ_ONLY            178  // payload: 1B value (0/1); writes ComPrefs.allow_read_only; multi_role only
#define BEEBO_CMD_GET_AGC_RESET_INTERVAL         179  // reply OK + value (1B) = ComPrefs.agc_reset_interval/4, seconds; multi_role only
#define BEEBO_CMD_SET_AGC_RESET_INTERVAL         180  // payload: 1B value, seconds; writes ComPrefs.agc_reset_interval * 4; multi_role only
#define BEEBO_CMD_GET_LOOP_DETECT                181  // reply OK + value (1B) = ComPrefs.loop_detect mode (0=off,1=minimal,2=moderate,3=strict); multi_role only
#define BEEBO_CMD_SET_LOOP_DETECT                182  // payload: 1B value (0-3, same mode encoding); writes ComPrefs.loop_detect; multi_role only
#define BEEBO_CMD_GET_FLOOD_ADVERT_INTERVAL      183  // reply OK + value (1B) = ComPrefs.flood_advert_interval, minutes; multi_role only
#define BEEBO_CMD_SET_FLOOD_ADVERT_INTERVAL      184  // payload: 1B value, minutes; writes ComPrefs.flood_advert_interval; multi_role only
#define BEEBO_CMD_GET_INTERFERENCE_THRESHOLD     185  // reply OK + value (1B) = ComPrefs.interference_threshold; multi_role only
#define BEEBO_CMD_SET_INTERFERENCE_THRESHOLD     186  // payload: 1B value; writes ComPrefs.interference_threshold; multi_role only
#define BEEBO_CMD_GET_ADVERT_INTERVAL            187  // reply OK + value (1B) = ComPrefs.advert_interval/2, minutes; multi_role only
#define BEEBO_CMD_SET_ADVERT_INTERVAL            188  // payload: 1B value, minutes; writes ComPrefs.advert_interval * 2; multi_role only
#define BEEBO_CMD_GET_FLOOD_MAX                  189  // reply OK + value (1B) = ComPrefs.flood_max; multi_role only
#define BEEBO_CMD_SET_FLOOD_MAX                  190  // payload: 1B value; writes ComPrefs.flood_max; multi_role only
#define BEEBO_CMD_GET_FLOOD_MAX_UNSCOPED         191  // reply OK + value (1B) = ComPrefs.flood_max_unscoped; multi_role only
#define BEEBO_CMD_SET_FLOOD_MAX_UNSCOPED         192  // payload: 1B value; writes ComPrefs.flood_max_unscoped; multi_role only
#define BEEBO_CMD_GET_FLOOD_MAX_ADVERT           193  // reply OK + value (1B) = ComPrefs.flood_max_advert; multi_role only
#define BEEBO_CMD_SET_FLOOD_MAX_ADVERT           194  // payload: 1B value; writes ComPrefs.flood_max_advert; multi_role only
#define BEEBO_CMD_GET_OWNER_INFO                 195  // reply OK + owner info bytes (no NUL, up to 119); multi_role only
#define BEEBO_CMD_SET_OWNER_INFO                 196  // payload: owner info string bytes (no NUL, up to 119); writes ComPrefs.owner_info; multi_role only
#define BEEBO_CMD_SET_REPEATER_PASSWORD          197  // payload: password string bytes (no NUL, up to 15); write-only, updates RAM + ComPrefs; multi_role only
#define BEEBO_CMD_SET_GUEST_PASSWORD             198  // payload: password string bytes (no NUL, up to 15); write-only, updates RAM + ComPrefs; multi_role only
#define BEEBO_CMD_GET_REPEATER_PASSWORD_SET      228  // reply OK + value (4B LE) = 1 if repeater.password differs from the firmware's built-in default ("password"), 0 if it's still the default -- mirrors GET_WIFI_PWD_SET's shape, but compares against the known default server-side rather than just checking non-empty (the password is never empty by construction, it always has a value); never the password itself; multi_role only
#define BEEBO_CMD_REBOOT_WITH_TIME               229  // payload: 4B LE uint32 epoch seconds (the caller's own current clock); same as the plain reboot command, but uses this timestamp instead of the device's own current time for both the NVS RTC backup (see ESP32Board.h's beebo_persistRTCTimeForReboot()/rebootWithTime()) and a live clock correction applied immediately before restarting -- for a device whose live clock is itself wrong, where every ordinary reboot just re-persists (and never corrects) the same bad value. The live-clock correction is safe specifically because it's immediately followed by esp_restart() with nothing else running in between -- no in-flight timer/deadline logic ever observes the jump. No reply -- the device restarts immediately, same as the plain reboot command
#define BEEBO_CMD_GET_REGION_HOME                230  // reply REGION_HOME + home region name bytes (no NUL, may be 0 bytes if no home region is set); RegionMap-backed (src/helpers/RegionMap.h), not a ComPrefs/NodePrefs field -- separate persistence (region_map.save()), not covered by GET/SET_PREFS_TLV; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region home' (get form)
#define BEEBO_CMD_SET_REGION_HOME                231  // payload: region name string bytes (no NUL); empty payload clears the home region; '*' (RegionMap's built-in wildcard/catch-all entry) is rejected -- setting home to it can never be read back correctly (getHomeRegion() doesn't resolve it). The name must already exist (define one first with SET_REGION_PUT or a RepeaterLink's text-CLI 'region put <name>') or ERR_CODE_NOT_FOUND is returned; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region home <name>' (set form)
#define BEEBO_CMD_GET_REGION_LIST                232  // reply REGION_LIST + comma-separated region names (no NUL), via RegionMap::exportNamesTo() with no flood-allow/deny filtering (every defined region, not just flood-allowed ones) -- flat names only, no parent/hierarchy or flood-flag info; see GET_REGION_TREE for that. Read-only; multi_role only, repeater role
#define BEEBO_CMD_GET_REGION_TREE                233  // reply REGION_TREE + RegionMap::exportTo()'s full hierarchical text export (no NUL): one line per region, indented by tree depth, each line '<name>[^][ F]' where ^ marks the home region and a trailing ' F' marks flood-allowed (absence means flood-denied) -- same format/content as CommonCLI's text-CLI bare 'region' command. Read-only; multi_role only, repeater role
#define BEEBO_CMD_SET_REGION_PUT                 234  // payload: name\0parent\0 (name required; parent optional -- empty or omitted means the wildcard root, matching CommonCLI's 'region put <name> [parent]' default). Creates the region if it doesn't exist (flood-allowed by default, matching CommonCLI's own post-put reset) or re-parents it if it does; ERR_CODE_NOT_FOUND if a non-empty parent name doesn't exist, ERR_CODE_TABLE_FULL if MAX_REGION_ENTRIES is reached. Auto-persists (region_map.save()) on success, unlike CommonCLI's text-CLI which needs an explicit 'region save' after 'region put'; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region put'
#define BEEBO_CMD_SET_REGION_REMOVE              235  // payload: region name string bytes (no NUL). ERR_CODE_NOT_FOUND if it doesn't exist; ERR_CODE_ILLEGAL_ARG if it still has child regions (RegionMap::removeRegion() refuses to remove a non-empty parent -- remove or re-parent its children first). Auto-persists on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region remove'
#define BEEBO_CMD_SET_REGION_ALLOWF              236  // payload: region name string bytes (no NUL); clears that region's REGION_DENY_FLOOD flag (flood-allowed). ERR_CODE_NOT_FOUND if it doesn't exist. Auto-persists on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region allowf'
#define BEEBO_CMD_SET_REGION_DENYF               237  // payload: region name string bytes (no NUL); sets that region's REGION_DENY_FLOOD flag (flood-denied). ERR_CODE_NOT_FOUND if it doesn't exist. Auto-persists on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region denyf'
#define BEEBO_CMD_SET_REGION_DEF                 241  // payload: def string bytes (no NUL), same space-separated multi-segment DSL as CommonCLI's text-CLI 'region def <segments>': each segment is 'name' or 'name|jump'/'name,jump' (define 'name' under the current cursor -- wildcard root at the start -- then move the cursor to 'jump', an existing region found by name-prefix match, or stay at the newly-defined 'name' if no jump is given). Lets one command build a whole subtree instead of N 'region put' round trips. Each new region is flood-allowed by default (same as SET_REGION_PUT). ERR_CODE_ILLEGAL_ARG on an empty name or empty jump target, ERR_CODE_NOT_FOUND on an unresolvable jump target, ERR_CODE_TABLE_FULL if MAX_REGION_ENTRIES is reached -- the whole def is applied segment-by-segment and stops at the first error (already-applied segments before it are NOT rolled back, matching CommonCLI's own 'region def' behavior). Auto-persists (region_map.save()) on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region def'
#define BEEBO_CMD_SET_REGION_SAVE                242  // no payload; explicitly persists region_map to flash (region_map.save()). Every other SET_REGION_* opcode already auto-persists on success, so this is a no-op in practice for binary-mode devices -- it exists purely for backward compatibility with CommonCLI's text-CLI 'region save', which callers may still send out of habit after a 'region put'/'region def'. Replies OK on success, ERR_CODE_FILE_IO_ERROR if the flash write itself failed (mirrors CommonCLI's text-CLI 'region save' surfacing its own saveRegions() callback's result). multi_role only, repeater role
#define BEEBO_CMD_GET_REGION_DEFAULT             205  // reply REGION_DEFAULT + default-region name bytes (no NUL, may be 0 bytes if no default region is set); RegionMap's own independent default_id (RegionMap::getDefaultRegion()), distinct from home_id/GET_REGION_HOME -- restores stock simple_repeater's own default-scope mechanism (MyMesh.cpp begin()/onDefaultRegionChanged()), which multi_role's repeater role hadn't wired to any consumer until this addition (it was instead borrowing companion's node.region.scope/default_scope_key as a stand-in -- see kbase/PROTOCOL_AND_SETTINGS_STORAGE.md). Not covered by GET/SET_PREFS_TLV, same as GET_REGION_HOME; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region default' (get form)
#define BEEBO_CMD_SET_REGION_DEFAULT             206  // payload: region name string bytes (no NUL); empty payload clears the default region. Unlike SET_REGION_HOME, auto-creates the named region (flood-allowed) if it doesn't exist yet, matching CommonCLI's text-CLI 'region default <name>' exactly (CommonCLI.cpp's own handleRegionCmd auto-creates via putRegion there too) rather than SET_REGION_HOME's stricter ERR_CODE_NOT_FOUND -- ERR_CODE_TABLE_FULL if MAX_REGION_ENTRIES is reached and no existing region matches. Auto-persists (region_map.save()) on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region default <name>' (set form)
#define BEEBO_CMD_SET_NEIGHBOR_REMOVE            238  // payload: [len:1][pubkey:len] (len 1-32). Prunes the matching entry from the direct (zero-hop) neighbour table -- RAM-only, not persisted, re-populated as adverts are heard again -- using the same prefix-match convention Beebo::putNeighbour() uses for matching an existing slot (compares over min(len, stored pubkey_len) bytes). ERR_CODE_NOT_FOUND if no neighbour matches. Mirrors CommonCLI's text-CLI 'neighbor.remove <hex>'
#define BEEBO_CMD_GET_FULL_VERSION               199  // reply FULL_VERSION + untruncated FIRMWARE_VERSION bytes (no NUL); the standard DEVICE_INFO frame's ver field is a fixed 20 bytes upstream, too short for beebo's mode-suffixed versions (e.g. "...dbg")
#define BEEBO_CMD_GET_REPEATER_NAME              209  // reply REPEATER_NAME + repeater-role name bytes (no NUL, up to 31); stored at /com_prefs offset 4 (same on-disk position simple_repeater's own NodePrefs.node_name used); empty if never set, no fallback to the companion name (removed -- reads repeater's own resident slot directly, regardless of which role is live); multi_role only
#define BEEBO_CMD_SET_REPEATER_NAME              210  // payload: name string bytes (no NUL, up to 31); writes /com_prefs offset 4; multi_role only
#define BEEBO_CMD_CLEAR_PROFILE                  211  // reset the command-latency profiling ring (STATS_TYPE_PROFILE) to empty
#define BEEBO_CMD_GET_PREFS_TLV                  212  // one round trip for every field in Beebo.h's PREFS_TLV_KEY_* table, as TLV triplets [key:1][len:1][value:len]; multi_role only
#define BEEBO_CMD_SET_PREFS_TLV                  213  // payload is one or more [key:1][len:1][value:len] triplets to change -- only the fields being written need to be sent (unlike GET_PREFS_TLV's full dump); one flash write covers every ComPrefs triplet in the payload, however many; multi_role only
#define BEEBO_CMD_GET_TUNE_ENABLED               214  // reply OK + value (1B) = dynamic-tuning optimizer on/off (RAM-only, see DYNAMIC_OPTIMIZER_PLAN.md; always 0 after reboot); multi_role only
#define BEEBO_CMD_SET_TUNE_ENABLED               215  // payload: 1B value (0/1); RAM-only -- never calls a NodePrefs/ComPrefs setter regardless of this switch (observe-only Phase A); multi_role only
#define BEEBO_CMD_GET_TUNE_APPLIED_MASK          216  // reply OK + value (1B) = per-param live-actuation bitmask, bit i = TuneController::specFor(i)'s param_id (RAM-only, always 0 after reboot); multi_role only
#define BEEBO_CMD_SET_TUNE_APPLIED_MASK          217  // payload: 1B bitmask; RAM-only. A set bit lets that TUNE_* param's proposals actually be written (see TuneController::Decision/Beebo::applyTuneDecision); 0 (default) keeps every param observe-only; multi_role only
#define BEEBO_CMD_GET_REPEATER_RXDELAY           218  // reply OK + value (4B float bits) = repeater's own rx_delay_base, independent of the shared companion value CMD_GET_TUNING_PARAMS returns (SETTINGS_TREE_CLEANUP.md Decision A); stored at /com_prefs offset 80 (simple_repeater's own NodePrefs slot); multi_role only
#define BEEBO_CMD_SET_REPEATER_RXDELAY           219  // payload: 4B float bits; writes /com_prefs offset 80; multi_role only
#define BEEBO_CMD_GET_REPEATER_AIRTIME           220  // reply OK + value (4B float bits) = repeater's own airtime_factor, independent of the shared companion value CMD_GET_TUNING_PARAMS returns (SETTINGS_TREE_CLEANUP.md Decision A); stored at /com_prefs offset 0 (simple_repeater's own NodePrefs slot); multi_role only
#define BEEBO_CMD_SET_REPEATER_AIRTIME           221  // payload: 4B float bits; writes /com_prefs offset 0; multi_role only
#define BEEBO_CMD_GET_ACK_STATS                  222  // reply RESP_CODE_BEEBO/ACK_STATS: ack_success_count (4B u32) + ack_timeout_count (4B u32) + ack_overflow_count (4B u32), lifetime counts of confirmed-delivered/timed-out direct-message sends (BaseChatMesh::getAckSuccessCount/getAckTimeoutCount) plus how many times Beebo::expected_ack_table's ring wrapped onto a still-unresolved slot before it could time out properly -- a real starvation event, not a no-op (Beebo::getAckOverflowCount, DYNAMIC_OPTIMIZER_PLAN.md item 9 -- "TX reception confirmation"); companion only, RAM-only (0 after reboot)
#define BEEBO_CMD_GET_ECHO_COUNT                 223  // reply RESP_CODE_BEEBO/ECHO_STATS: echo_success_count (4B u32) + echo_timeout_count (4B u32) + echo_overflow_count (4B u32) + self_tx_direct_count (4B u32) -- lifetime counts of confirmed-heard vs. confirmed-timed-out flood self-transmissions (SimpleMeshTables::getEchoSuccessCount/getEchoTimeoutCount), how many times the echo ring wrapped onto a still-unresolved slot before it reached either verdict (SimpleMeshTables::getEchoOverflowCount), plus how many self-transmissions were direct-routed and therefore structurally excluded from ECHO tracking entirely -- a direct/addressed packet can't come back as a flood echo (SimpleMeshTables::getSelfTxDirectCount, DYNAMIC_OPTIMIZER_PLAN.md item 9); RAM-only (0 after reboot)
#define BEEBO_CMD_GET_DEDUP_WINDOW               224  // reply OK + value (4B LE) = milliseconds [0 to 60000]; 0 is a real, literal value -- disables live-eviction counting entirely (see SimpleMeshTables::hasSeen(), millis()-resolution, not RTC-second), not a default sentinel -- companion value; the dedup-table eviction count itself is already in GET_MONRING's header (rx_dedup_table_full_count, gated to only count evictions still within this window); see GET_REPEATER_DEDUP_WINDOW for the independent repeater copy
#define BEEBO_CMD_SET_DEDUP_WINDOW               225  // payload: 4B LE uint32 milliseconds [0 to 60000]; 0 disables live-eviction counting entirely; out-of-range rejected (ERR_CODE_ILLEGAL_ARG); persisted; companion value -- see SET_REPEATER_DEDUP_WINDOW for the independent repeater copy
#define BEEBO_CMD_GET_REPEATER_DEDUP_WINDOW      226  // reply OK + value (4B LE) = milliseconds [0 to 60000] -- repeater's own independent dedup live-eviction window (SETTINGS_TREE_CLEANUP.md Decision A pattern, like GET_REPEATER_RXDELAY/GET_REPEATER_AIRTIME); stored at /beebo_repeater, its own file (moved off a /com_prefs offset-439 shadow byte once CommonCLI's real savePrefs() became the /com_prefs write path -- that truncates to ComPrefs's own struct length on every save); multi_role only
#define BEEBO_CMD_SET_REPEATER_DEDUP_WINDOW      227  // payload: 4B LE uint32 milliseconds [0 to 60000]; 0 disables live-eviction counting entirely; out-of-range rejected (ERR_CODE_ILLEGAL_ARG); writes /beebo_repeater (see GET_REPEATER_DEDUP_WINDOW); multi_role only
#define BEEBO_CMD_GET_MONRING_EVENT_MASK         239  // reply OK + value (4B LE) = per-event-type MON_EVENT capture bitmask, bit N = MonRing.h's EVENT_* id N; 1=captured. RAM-only (all-1s/capture-everything after reboot), independent of the per-kind monring_config MON_CAP_EVENT bit (that bit gates MON_EVENT capture at all; this mask further filters which event TYPES within it are kept -- capture is expensive per DYNAMIC_OPTIMIZER_PLAN.md, most event types are low-volume faults worth always keeping, a few (e.g. tx_ack_success/tx_echo_success) can be high-volume on a busy node and worth excluding without losing the rest)
#define BEEBO_CMD_SET_MONRING_EVENT_MASK         240  // payload: 4B LE uint32 bitmask, same encoding as GET_MONRING_EVENT_MASK; RAM-only, not persisted
#define BEEBO_CMD_NODE_DISCOVER                  243  // actively query nearby nodes for their identity, rather than waiting on their next periodic self-advert (CTL_TYPE_NODE_DISCOVER_REQ/RESP, see Beebo::sendNodeDiscoverReq()). payload: [filter:1][prefix_only:1]; filter is a bitmask of (1 << ADV_TYPE_*) -- e.g. (1<<ADV_TYPE_REPEATER)|(1<<ADV_TYPE_SENSOR) to ask for repeaters and sensors -- ERR_CODE_ILLEGAL_ARG if 0; prefix_only=1 asks responders to reply with only an 8-byte pubkey prefix instead of the full 32 bytes. Replies OK immediately (the request is a zero-hop broadcast, sent and forgotten); matching CTL_TYPE_NODE_DISCOVER_RESP replies trickle in over the following ~60s and are logged into the existing direct (zero-hop) neighbour table (Beebo::putNeighbour()), same as GET_NEIGHBORS already streams -- poll that command after a short wait to see results. Not role-gated: any role can ask 'who's near me'; only nodes whose own current type matches a set filter bit answer (CTL_TYPE_NODE_DISCOVER_REQ handling in onControlDataRecv(), also not role-gated -- a companion node answers as ADV_TYPE_CHAT, a repeater as ADV_TYPE_REPEATER). Mirrors CommonCLI's text-CLI 'discover.neighbors [repeater|chat|room|sensor|all ...]'
#define BEEBO_CMD_GET_ADVERT_PATHS               244  // stream the WHOLE advert_paths[] cache (ADVERT_PATH_TABLE_SIZE=16 entries, LRU by recv_timestamp) in one round trip, no payload -- the bulk counterpart to upstream's single-pubkey CMD_GET_ADVERT_PATH (0x2a). Match each entry's pubkey_prefix locally against however many contacts the caller cares about instead of issuing one CMD_GET_ADVERT_PATH per contact: the cache only ever holds 16 entries total regardless of contact-list size, so a per-contact loop is always doing 16 real answers' worth of work spread over however many round trips there are contacts, for no benefit over one bulk read. Same START/entry/END streaming shape as GET_NEIGHBORS
#define BEEBO_CMD_GET_ROLE_PUBLIC_KEY            245  // payload: 1 byte role (NODE_ROLE_COMPANION=0/NODE_ROLE_REPEATER=1); reply RESP_CODE_BEEBO/ROLE_PUBLIC_KEY with that role's own 32-byte Ed25519 public key, regardless of which role is currently live (PER_ROLE_IDENTITY plan) -- self_info only ever reflects the live role's identity, so companion.public_key/repeater.public_key settings leaves read through this instead. ERR_CODE_ILLEGAL_ARG if role isn't 0/1; ERR_CODE_NOT_FOUND if that role has never been switched into on this device yet (its identity file doesn't exist) -- a GET must never have the side effect of creating one
#define BEEBO_CMD_GET_BOARD_ID                   246  // no payload; reply RESP_CODE_BEEBO/BOARD_ID with the ESP32's 6-byte factory eFuse base MAC (esp_efuse_mac_get_default()) -- a hardware-burned identifier, stable across reflashes/identity changes/role switches, independent of node.public_key (ed25519, unrelated to the MAC) and of node.role (shared across both). Not a wire MAC address (no per-interface offset applied, see esp_read_mac()), just a unique per-board ID
#define BEEBO_CMD_GET_BOARD_NAME                 251  // no payload; reply RESP_CODE_BEEBO/BOARD_NAME with BeeboCompanionPrefs.board_name bytes (no NUL, may be empty). Human-editable alias for this physical board's identity (board.id, the read-only eFuse MAC) -- distinct from the per-role persona names (companion.name/repeater.name, see GET_ROLE_NAME): board.name identifies the hardware, not a role. Role-agnostic -- BeeboCompanionPrefs is compiled into every build (multi_role, static companion, static repeater), same as owner_password. Empty until the operator sets one (see beebo/plans/DEVICE_NAME.md); `beebo config`'s default filenames fall back to board.id's hex string until then
#define BEEBO_CMD_SET_BOARD_NAME                 252  // payload: name string bytes (no NUL, up to 31); updates RAM + BeeboCompanionPrefs.board_name. Purely a local label -- unlike node.owner.password this has no gating/security role, it's just a friendlier name than board.id's raw hex for a human to recognize the device by
#define BEEBO_CMD_SET_OWNER_PASSWORD             248  // payload: password string bytes (no NUL, up to 15); write-only, updates RAM + BeeboCompanionPrefs.owner_password. Role-agnostic -- BeeboCompanionPrefs is compiled into every build (multi_role, static companion, static repeater), unlike ComPrefs/repeater.password which only exists when BEEBO_ENABLE_REPEATER_ROLE=1. This is the node's one backup/recovery credential (see UNLOCK_ROLE_SECRETS below), distinct from repeater.password (mesh admin login, only meaningful when the repeater role is actually compiled in)
#define BEEBO_CMD_GET_OWNER_PASSWORD_SET         249  // reply OK + value (4B LE) = 1 if node.owner.password has ever been set (non-empty), 0 if still unset -- unlike repeater.password there's no compiled-in default to compare against (empty is the only unset state); never the password itself
#define BEEBO_CMD_GET_ROLE_NAME                  250  // payload: 1 byte role (NODE_ROLE_COMPANION=0/NODE_ROLE_REPEATER=1); reply RESP_CODE_BEEBO/ROLE_NAME with that role's own name, regardless of which role is currently live -- reads that role's own resident role_state_store[] slot directly (never the live role's slot), mirrors GET_ROLE_PUBLIC_KEY. NODE_ROLE_COMPANION replies NodePrefs.node_name; NODE_ROLE_REPEATER replies ComPrefs.node_name; empty if that role's name was never set, no fallback between roles (removed -- see GET_REPEATER_NAME's own desc). companion.name/repeater.name settings leaves and anything else that needs a role's own name irrespective of what's live (`beebo config pull/diff/push --role`, ...) read through here -- RESP_CODE_SELF_INFO's own "name" field is live-role-scoped (swaps with type/pubkey per GET_NODE_ROLE's hot-switch, see that reply's own comment), so it's only correct for whichever role is actually live, not an arbitrary target role. Always succeeds for either role (unlike GET_ROLE_PUBLIC_KEY, a name isn't gated on that role's identity having ever been created). ERR_CODE_ILLEGAL_ARG if role isn't 0/1
#define BEEBO_CMD_GET_COMPANION_MULTI_ACKS         0  // no payload; reply OK + value (4B LE) = companion's own _prefs.multi_acks, regardless of which role is currently live -- mirrors GET_ROLE_NAME's rationale but only for the companion side (repeater already has this via BEEBO_CMD_GET_REPEATER_MULTI_ACKS, always com_prefs, unconditional). RESP_CODE_SELF_INFO's own multi_acks field is live-role-scoped (swaps to com_prefs.multi_acks when repeater is live, see CMD_APP_START's self-info reply comment), so it's only correct for whichever role is actually live -- companion.multi_acks (prefs.py) reads through here instead so it can't silently return repeater's value over a binary connection while repeater is live
#define BEEBO_CMD_GET_COMPANION_PATH_HASH_MODE     1  // no payload; reply OK + value (4B LE) = companion's own _prefs.path_hash_mode, regardless of which role is currently live -- same rationale and companion/repeater split as GET_COMPANION_MULTI_ACKS above (repeater's own is BEEBO_CMD_GET_REPEATER_PATH_HASH_MODE)
#define BEEBO_CMD_GET_COMPANION_LAT                2  // no payload; reply OK + value (4B LE, signed int32 degrees*1e6) = companion's own BeeboCompanionPrefs.node_lat (PREFS-mode coordinate, what CMD_SET_ADVERT_LATLON writes -- NOT the shared sensors.node_lat SHARE-mode register), regardless of which role is currently live -- same rationale as GET_COMPANION_MULTI_ACKS above (repeater's own is BEEBO_CMD_GET_REPEATER_LAT); paired with GET_COMPANION_LON the same way GET_REPEATER_LAT/_LON are paired, not a combined coords opcode
#define BEEBO_CMD_GET_COMPANION_LON                3  // no payload; reply OK + value (4B LE, signed int32 degrees*1e6) = companion's own BeeboCompanionPrefs.node_lon (PREFS-mode coordinate) -- see GET_COMPANION_LAT
#define BEEBO_CMD_GET_COMPANION_ADV_LOC_POLICY     4  // no payload; reply OK + value (4B LE) = companion's own _prefs.advert_loc_policy, regardless of which role is currently live -- same rationale and gap as GET_COMPANION_MULTI_ACKS above: CMD_SET_OTHER_PARAMS always writes _prefs.advert_loc_policy unconditionally, but the only GET was RESP_CODE_SELF_INFO's own advert_loc_policy field, live-role-scoped once repeater got its own copy (see GET_REPEATER_ADV_LOC_POLICY); companion.adv_loc_policy (prefs.py) reads through here instead
#define BEEBO_CMD_GET_REPEATER_TRANSPORT_CONFIG    5  // no payload; reply OK + value (byte0=ble_enabled, byte1=tcp_enabled, byte2=usb_enabled) = repeater's own independent transport-enable flags, regardless of which role is currently live -- same SETTINGS_REFACTOR.md Part 3 follow-up rationale as GET_REPEATER_MULTI_ACKS: GET_TRANSPORT_CONFIG always reads whichever role is live, so config pull/push --role can't otherwise capture repeater's own flags while companion is live; stored at /beebo_repeater
#define BEEBO_CMD_SET_REPEATER_TRANSPORT_CONFIG    6  // payload: [ble_enabled][tcp_enabled][usb_enabled] (no reboot byte -- unlike SET_TRANSPORT_CONFIG, this may target a non-live role, where 'reboot to apply' has no meaning); writes /beebo_repeater. Applies the same ble/tcp-mutually-exclusive and never-leave-node-unreachable (usb auto-enable) invariants as SET_TRANSPORT_CONFIG. Live-applies (signals main.cpp the same way SET_TRANSPORT_CONFIG does) only if repeater happens to already be the live role; otherwise takes effect the next time repeater becomes live
#define BEEBO_CMD_GET_COMPANION_TRANSPORT_CONFIG   7  // no payload; reply OK + value, same byte layout as GET_REPEATER_TRANSPORT_CONFIG -- companion's own independent transport-enable flags, regardless of which role is currently live; stored at /beebo_companion
#define BEEBO_CMD_SET_COMPANION_TRANSPORT_CONFIG   8  // payload: [ble_enabled][tcp_enabled][usb_enabled], same shape and invariants as SET_REPEATER_TRANSPORT_CONFIG -- writes /beebo_companion, live-applies only if companion is the live role
#define BEEBO_CMD_GET_REPEATER_WIFI_SSID           9  // no payload; reply RESP_CODE_BEEBO/WIFI_SSID (same response shape as GET_WIFI_SSID) = repeater's own independent wifi_ssid, regardless of which role is currently live; stored at /beebo_repeater
#define BEEBO_CMD_GET_REPEATER_WIFI_PWD_SET       10  // no payload; reply OK + value (4B LE) = 1 if repeater's own wifi_pwd is non-empty, 0 otherwise (same shape as GET_WIFI_PWD_SET), regardless of which role is currently live; never the password itself
#define BEEBO_CMD_SET_REPEATER_WIFI_CREDS         11  // payload: ssid\0pwd\0 (same shape as SET_WIFI_CREDS, empty segment = leave unchanged) -- writes repeater's own wifi_ssid/wifi_pwd at /beebo_repeater, regardless of which role is currently live. Live-applies (signals main.cpp to start WiFi, same as SET_WIFI_CREDS) only if repeater happens to already be the live role; otherwise takes effect the next time repeater becomes live. WIFI_CREDS_REBOOT's reboot-to-apply build option is not honoured here -- rebooting only makes sense for the live role
#define BEEBO_CMD_GET_COMPANION_WIFI_SSID         12  // no payload; reply RESP_CODE_BEEBO/WIFI_SSID, same shape as GET_REPEATER_WIFI_SSID -- companion's own independent wifi_ssid, regardless of which role is currently live; stored at /beebo_companion
#define BEEBO_CMD_GET_COMPANION_WIFI_PWD_SET      13  // no payload; reply OK + value (4B LE), same shape as GET_REPEATER_WIFI_PWD_SET -- 1 if companion's own wifi_pwd is non-empty; never the password itself
#define BEEBO_CMD_SET_COMPANION_WIFI_CREDS        14  // payload: ssid\0pwd\0, same shape and live-apply rule as SET_REPEATER_WIFI_CREDS -- writes companion's own wifi_ssid/wifi_pwd at /beebo_companion
#define BEEBO_CMD_GET_REPEATER_BLE_PIN            15  // no payload; reply OK + value (4B LE) = repeater's own stored ble_pin override (0 = unset, falls back to BLE_PIN_CODE), regardless of which role is currently live -- the *stored* value, not the resolved *active* session pin CMD_DEVICE_QUERY's DEVICE_INFO reply reports (which is always live-role-scoped); same semantics as repeater's own text-CLI 'get ble.pin'. Stored at /beebo_repeater
#define BEEBO_CMD_SET_REPEATER_BLE_PIN            16  // payload: 4B LE value -- 0 (unset) or a 6-digit pin (100000-999999), ERR_CODE_ILLEGAL_ARG otherwise; writes /beebo_repeater. Live-applies (moves _active_ble_pin/the BLE stack's pin the same way CMD_SET_DEVICE_PIN does) only if repeater happens to already be the live role; otherwise takes effect the next time repeater becomes live
#define BEEBO_CMD_GET_COMPANION_BLE_PIN           17  // no payload; reply OK + value (4B LE), same shape and stored-vs-active distinction as GET_REPEATER_BLE_PIN -- companion's own stored ble_pin override. Stored at /beebo_companion
#define BEEBO_CMD_SET_COMPANION_BLE_PIN           18  // payload: 4B LE value, same shape and live-apply rule as SET_REPEATER_BLE_PIN -- writes /beebo_companion
#define BEEBO_CMD_UNLOCK_ROLE_SECRETS            247  // payload: [candidate password bytes, up to 15, no NUL] -- checked against BeeboCompanionPrefs.owner_password (see SET_OWNER_PASSWORD), the node's single role-agnostic backup credential, present on every build regardless of which role(s) are compiled in. A mismatch AND an unset (empty) owner_password both fail closed -- unlocking is never possible until the owner has explicitly set this password at least once. Password-gated secret readback for `beebo config backup` (see beebo/plans/SETTINGS_ISOLATION.md): proves the caller already knows the owner password rather than exposing anything to a bare-reachable, unauthenticated session (multi_role's WiFi/TCP companion transport has no other authentication at all, unlike BLE's paired PIN or USB's physical possession -- this keeps a WiFi-only attacker from harvesting secrets they don't already know). On match, replies RESP_CODE_BEEBO/ROLE_SECRETS with repeater.guest.password + NUL + node.wifi.password + NUL + repeater.password, always in that order (any may be empty; the two repeater-only fields are always empty on a BEEBO_ENABLE_REPEATER_ROLE=0 build, which has no ComPrefs at all) -- one verified owner password unlocks every secret on the device, no separate proof needed per secret, since a session that already knows the owner password already has unrestricted write access to all of them (a companion session can already overwrite any of them blind, with no gate at all) -- reading their current values back is a strictly smaller exposure than that existing write access. A plain EventType.ERROR reply (not a distinct error code -- deliberately indistinguishable from a malformed request) on a mismatched/unset candidate, so a failed guess doesn't confirm anything about the real password's shape/length beyond what a normal login attempt already would. Available on every build, static or dynamic -- no ERR_CODE_UNSUPPORTED_CMD case anymore
#define BEEBO_CMD_GET_REPEATER_MULTI_ACKS        253  // reply OK + value (1B, 0/1) = repeater's own independent multi_acks, independent of the shared companion value CMD_DEVICE_QUERY/self_info report (SETTINGS_TREE_CLEANUP.md Decision A pattern, like GET_REPEATER_RXDELAY/GET_REPEATER_AIRTIME); stored at /beebo_repeater (ComPrefs.multi_acks, same struct offset stock simple_repeater's own NodePrefs.multi_acks uses); multi_role only
#define BEEBO_CMD_SET_REPEATER_MULTI_ACKS        254  // payload: 1B value, constrained to 0/1; writes /beebo_repeater; multi_role only
#define BEEBO_CMD_GET_REPEATER_PATH_HASH_MODE    255  // reply OK + value (1B, 0-2) = repeater's own independent path_hash_mode, independent of the shared companion value (SETTINGS_TREE_CLEANUP.md Decision A pattern); stored at /beebo_repeater (ComPrefs.path_hash_mode); multi_role only
#define BEEBO_CMD_SET_REPEATER_PATH_HASH_MODE    200  // payload: 1B value 0-2; ERR_CODE_ILLEGAL_ARG if >=3; writes /beebo_repeater; multi_role only
#define BEEBO_CMD_GET_REPEATER_LAT               201  // reply OK + value (4B LE int32, degrees*1e6) = repeater's own independent node_lat, independent of the shared companion value (SETTINGS_TREE_CLEANUP.md Decision A pattern); stored at /beebo_repeater (ComPrefs.node_lat); multi_role only
#define BEEBO_CMD_SET_REPEATER_LAT               202  // payload: 4B LE int32, degrees*1e6, range [-90e6, 90e6]; ERR_CODE_ILLEGAL_ARG if out of range; writes /beebo_repeater; multi_role only
#define BEEBO_CMD_GET_REPEATER_LON               203  // reply OK + value (4B LE int32, degrees*1e6) = repeater's own independent node_lon, independent of the shared companion value (SETTINGS_TREE_CLEANUP.md Decision A pattern); stored at /beebo_repeater (ComPrefs.node_lon); multi_role only
#define BEEBO_CMD_SET_REPEATER_LON               204  // payload: 4B LE int32, degrees*1e6, range [-180e6, 180e6]; ERR_CODE_ILLEGAL_ARG if out of range; writes /beebo_repeater; multi_role only
#define BEEBO_CMD_GET_REPEATER_ADV_LOC_POLICY    207  // reply OK + value (1B, 0-2) = repeater's own independent advert_loc_policy, independent of the shared companion value (SETTINGS_TREE_CLEANUP.md Decision A pattern, same split as GET_REPEATER_MULTI_ACKS/GET_REPEATER_PATH_HASH_MODE); stored at /beebo_repeater (ComPrefs.advert_loc_policy, same struct offset stock simple_repeater's own NodePrefs.advert_loc_policy uses -- see CommonCLI.h's 'gps advert' command, compiled out on beebo since ENV_INCLUDE_GPS=0, so this binary opcode is the only reachable way to view/change it for the repeater role); multi_role only. 0=none, 1=share (the shared, role-agnostic sensors.node_lat/lon live-GPS register -- stays exactly 0,0 on beebo, no GPS hardware compiled in; deliberately not seeded from prefs, so it's an obvious 0,0 rather than silently acting like 'prefs'), 2=prefs (com_prefs.node_lat/node_lon, this role's own persisted coordinate -- what BEEBO_CMD_SET_REPEATER_LAT/LON write)
#define BEEBO_CMD_SET_REPEATER_ADV_LOC_POLICY    208  // payload: 1B value 0-2; ERR_CODE_ILLEGAL_ARG if >=3; writes /beebo_repeater; multi_role only

// beebo response sub-ids (payload byte 0 after RESP_CODE_BEEBO)
#define BEEBO_RESP_OTA_BEGIN           200  // response to OTA_BEGIN
#define BEEBO_RESP_NEIGHBORS_START     201  // first reply to GET_NEIGHBORS: count + node time
#define BEEBO_RESP_NEIGHBOR            202  // one per direct neighbour
#define BEEBO_RESP_END_OF_NEIGHBORS    203  // last reply to GET_NEIGHBORS
#define BEEBO_RESP_MONRING             204  // reply to GET_MONRING: status header + records. Header's trailing reset:1 byte is 1 if the request's after_seq was overridden (after_ts predated the ring's current oldest resident record) and the reply starts from the oldest record instead, 0 if honored as given
#define BEEBO_RESP_XFER_CAPS           205  // (BULK_XFER): reply to SET_XFER_CAPS: granted [max_tx:2 LE][stream:1]
#define BEEBO_RESP_WIFI_SSID           206  // reply to GET_WIFI_SSID: ssid bytes (no NUL)
#define BEEBO_RESP_OWNER_INFO          207  // reply to GET_OWNER_INFO: owner info bytes (no NUL)
#define BEEBO_RESP_FULL_VERSION        208  // reply to GET_FULL_VERSION: untruncated FIRMWARE_VERSION bytes (no NUL)
#define BEEBO_RESP_REPEATER_NAME       209  // reply to GET_REPEATER_NAME: repeater-role name bytes (no NUL)
#define BEEBO_RESP_PREFS_TLV           210  // reply to GET_PREFS_TLV: TLV triplets, see that command's desc
#define BEEBO_RESP_ACK_STATS           211  // reply to GET_ACK_STATS: ack_success_count (4B u32 LE) + ack_timeout_count (4B u32 LE) + ack_overflow_count (4B u32 LE)
#define BEEBO_RESP_ECHO_STATS          212  // reply to GET_ECHO_COUNT: echo_success_count (4B u32 LE) + echo_timeout_count (4B u32 LE) + echo_overflow_count (4B u32 LE) + self_tx_direct_count (4B u32 LE)
#define BEEBO_RESP_REGION_HOME         213  // reply to GET_REGION_HOME: home region name bytes (no NUL, may be empty)
#define BEEBO_RESP_REGION_LIST         214  // reply to GET_REGION_LIST: comma-separated region name bytes (no NUL, may be empty)
#define BEEBO_RESP_REGION_TREE         215  // reply to GET_REGION_TREE: RegionMap::exportTo()'s hierarchical text export bytes (no NUL, may be empty)
#define BEEBO_RESP_ADVERT_PATHS_START  216  // first reply to GET_ADVERT_PATHS: count of populated advert_paths[] entries (4B LE)
#define BEEBO_RESP_ADVERT_PATH         217  // one per populated advert_paths[] entry: pubkey_prefix (7B) + name (32B, no NUL) + recv_timestamp (4B LE) + path_len (1B) + path (Packet::writePath-encoded, variable length per path_len)
#define BEEBO_RESP_END_OF_ADVERT_PATHS 218  // last reply to GET_ADVERT_PATHS
#define BEEBO_RESP_ROLE_PUBLIC_KEY     219  // reply to GET_ROLE_PUBLIC_KEY: that role's 32-byte Ed25519 public key
#define BEEBO_RESP_BOARD_ID            220  // reply to GET_BOARD_ID: 6-byte eFuse base MAC
#define BEEBO_RESP_ROLE_SECRETS        221  // reply to UNLOCK_ROLE_SECRETS on a matching candidate: repeater.guest.password + NUL + node.wifi.password + NUL + repeater.password (any may be empty)
#define BEEBO_RESP_ROLE_NAME           222  // reply to GET_ROLE_NAME: that role's own name bytes (no NUL)
#define BEEBO_RESP_BOARD_NAME          223  // reply to GET_BOARD_NAME: board.name bytes (no NUL, may be empty)
#define BEEBO_RESP_REGION_DEFAULT      224  // reply to GET_REGION_DEFAULT: default-region name bytes (no NUL, may be empty)
