#pragma once

// GENERATED FILE -- do not hand-edit. Source: protocol.yaml. Regenerate with `python tools/gen_protocol.py`.

// The only two upstream CMD/RESP slots beebo claims -- every beebo
// action is a flat u8 sub-id carried as the first payload byte after
// one of these.
#define CMD_BEEBO        222
#define RESP_CODE_BEEBO  223

// beebo command sub-ids (payload byte 0 after CMD_BEEBO)
#define BEEBO_CMD_OTA_BEGIN               1  // start OTA session
#define BEEBO_CMD_OTA_WRITE               2  // write firmware chunk
#define BEEBO_CMD_OTA_END                 3  // finalize and reboot. payload (optional): 4B LE uint32 epoch seconds, the caller's own current clock -- if present, used for the deferred restart's NVS persistence and live clock correction instead of this device's own current time (see REBOOT_WITH_TIME's own desc for why); omit for the old behavior
#define BEEBO_CMD_GET_SAVE_PREFS          4  // reply OK + value (byte0 = save_prefs, 1=on)
#define BEEBO_CMD_SET_SAVE_PREFS          5  // payload: 1 byte -- 0=off, 1=on, 2=restore(reload), 3=commit(write now)
#define BEEBO_CMD_SET_CW                  6  // bench CW carrier. payload: [on:1][max_secs:2 LE]; on=0 stops
#define BEEBO_CMD_SET_TX_OPTIMIZE         7  // PA optimization. payload: [on:1]; 1=paOptTable(default), 0=fixed/monotonic
#define BEEBO_CMD_GET_NEIGHBORS           8  // stream the direct (zero-hop) neighbour table
#define BEEBO_CMD_GET_MONRING             9  // read monitor ring. payload: [after_seq:4 LE] (optional) [after_ts:4 LE] (optional, capture-time epoch of the record at after_seq as the client last recorded it -- lets the firmware detect a reboot/clear/wraparound since then and override to a full read, since after_seq alone can alias across MonRing::_next_seq resetting to 0; see the reply's reset flag)
#define BEEBO_CMD_SET_MONRING            10  // control RX capture. payload: [op:1] 0=pause 1=resume 2=clear; setting the capture config itself is SET_PREFS_TLV(KEY_MONRING_CONFIG)'s job, not this opcode's
#define BEEBO_CMD_SET_XFER_CAPS          11  // (BULK_XFER): negotiate bulk-transfer caps. payload: [max_rx_frame:2 LE][flags:1]; flags bit0=accept streamed reads
#define BEEBO_CMD_APP_DISCONNECT         12  // disconnect the companion session
#define BEEBO_CMD_SEND_POKE              13  // originate a 'poke' to a contact. payload: [pub_key:PUB_KEY_SIZE]
#define BEEBO_CMD_GET_BATT_STATE         14  // reply OK + value (4B LE) = BATT_STATE_* (byte0); RAM-only live sensor state, not a PrefsTlv field
#define BEEBO_CMD_GET_QUIET              15  // reply OK + value (1B) = bench-quiet state (0=off, 1=on)
#define BEEBO_CMD_SET_QUIET              16  // payload: 1B value (0=off -> reboots, 1=on -> sleeps radio+FEM); RAM-only, not persisted
#define BEEBO_CMD_SET_BATT_STATE         17  // payload: 1B value = BATT_STATE_*; RAM-only, not persisted; re-seeds the trend anchor
#define BEEBO_CMD_GET_NODE_ROLE          18  // reply OK + value (4B LE) = NODE_ROLE_* (0=companion, 1=repeater); multi_role only
#define BEEBO_CMD_SET_NODE_ROLE          19  // payload: 1B value = NODE_ROLE_*; persisted; hot switch (immediate); multi_role only
#define BEEBO_CMD_REBOOT_WITH_TIME       20  // payload: 4B LE uint32 epoch seconds (the caller's own current clock); same as the plain reboot command, but uses this timestamp instead of the device's own current time for both the NVS RTC backup (see ESP32Board.h's beebo_persistRTCTimeForReboot()/rebootWithTime()) and a live clock correction applied immediately before restarting -- for a device whose live clock is itself wrong, where every ordinary reboot just re-persists (and never corrects) the same bad value. The live-clock correction is safe specifically because it's immediately followed by esp_restart() with nothing else running in between -- no in-flight timer/deadline logic ever observes the jump. No reply -- the device restarts immediately, same as the plain reboot command
#define BEEBO_CMD_GET_REGION_HOME        21  // reply REGION_HOME + home region name bytes (no NUL, may be 0 bytes if no home region is set); RegionMap-backed (src/helpers/RegionMap.h), not a ComPrefs/NodePrefs field -- separate persistence (region_map.save()), not covered by GET/SET_PREFS_TLV; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region home' (get form)
#define BEEBO_CMD_SET_REGION_HOME        22  // payload: region name string bytes (no NUL); empty payload clears the home region; '*' (RegionMap's built-in wildcard/catch-all entry) is rejected -- setting home to it can never be read back correctly (getHomeRegion() doesn't resolve it). The name must already exist (define one first with SET_REGION_PUT or a RepeaterLink's text-CLI 'region put <name>') or ERR_CODE_NOT_FOUND is returned; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region home <name>' (set form)
#define BEEBO_CMD_GET_REGION_LIST        23  // reply REGION_LIST + comma-separated region names (no NUL), via RegionMap::exportNamesTo() with no flood-allow/deny filtering (every defined region, not just flood-allowed ones) -- flat names only, no parent/hierarchy or flood-flag info; see GET_REGION_TREE for that. Read-only; multi_role only, repeater role
#define BEEBO_CMD_GET_REGION_TREE        24  // reply REGION_TREE + RegionMap::exportTo()'s full hierarchical text export (no NUL): one line per region, indented by tree depth, each line '<name>[^][ F]' where ^ marks the home region and a trailing ' F' marks flood-allowed (absence means flood-denied) -- same format/content as CommonCLI's text-CLI bare 'region' command. Read-only; multi_role only, repeater role
#define BEEBO_CMD_SET_REGION_PUT         25  // payload: name\0parent\0 (name required; parent optional -- empty or omitted means the wildcard root, matching CommonCLI's 'region put <name> [parent]' default). Creates the region if it doesn't exist (flood-allowed by default, matching CommonCLI's own post-put reset) or re-parents it if it does; ERR_CODE_NOT_FOUND if a non-empty parent name doesn't exist, ERR_CODE_TABLE_FULL if MAX_REGION_ENTRIES is reached. Auto-persists (region_map.save()) on success, unlike CommonCLI's text-CLI which needs an explicit 'region save' after 'region put'; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region put'
#define BEEBO_CMD_SET_REGION_REMOVE      26  // payload: region name string bytes (no NUL). ERR_CODE_NOT_FOUND if it doesn't exist; ERR_CODE_ILLEGAL_ARG if it still has child regions (RegionMap::removeRegion() refuses to remove a non-empty parent -- remove or re-parent its children first). Auto-persists on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region remove'
#define BEEBO_CMD_SET_REGION_ALLOWF      27  // payload: region name string bytes (no NUL); clears that region's REGION_DENY_FLOOD flag (flood-allowed). ERR_CODE_NOT_FOUND if it doesn't exist. Auto-persists on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region allowf'
#define BEEBO_CMD_SET_REGION_DENYF       28  // payload: region name string bytes (no NUL); sets that region's REGION_DENY_FLOOD flag (flood-denied). ERR_CODE_NOT_FOUND if it doesn't exist. Auto-persists on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region denyf'
#define BEEBO_CMD_SET_REGION_DEF         29  // payload: def string bytes (no NUL), same space-separated multi-segment DSL as CommonCLI's text-CLI 'region def <segments>': each segment is 'name' or 'name|jump'/'name,jump' (define 'name' under the current cursor -- wildcard root at the start -- then move the cursor to 'jump', an existing region found by name-prefix match, or stay at the newly-defined 'name' if no jump is given). Lets one command build a whole subtree instead of N 'region put' round trips. Each new region is flood-allowed by default (same as SET_REGION_PUT). ERR_CODE_ILLEGAL_ARG on an empty name or empty jump target, ERR_CODE_NOT_FOUND on an unresolvable jump target, ERR_CODE_TABLE_FULL if MAX_REGION_ENTRIES is reached -- the whole def is applied segment-by-segment and stops at the first error (already-applied segments before it are NOT rolled back, matching CommonCLI's own 'region def' behavior). Auto-persists (region_map.save()) on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region def'
#define BEEBO_CMD_SET_REGION_SAVE        30  // no payload; explicitly persists region_map to flash (region_map.save()). Every other SET_REGION_* opcode already auto-persists on success, so this is a no-op in practice for binary-mode devices -- it exists purely for backward compatibility with CommonCLI's text-CLI 'region save', which callers may still send out of habit after a 'region put'/'region def'. Replies OK on success, ERR_CODE_FILE_IO_ERROR if the flash write itself failed (mirrors CommonCLI's text-CLI 'region save' surfacing its own saveRegions() callback's result). multi_role only, repeater role
#define BEEBO_CMD_GET_REGION_DEFAULT     31  // reply REGION_DEFAULT + default-region name bytes (no NUL, may be 0 bytes if no default region is set); RegionMap's own independent default_id (RegionMap::getDefaultRegion()), distinct from home_id/GET_REGION_HOME -- restores stock simple_repeater's own default-scope mechanism (MyMesh.cpp begin()/onDefaultRegionChanged()), which multi_role's repeater role hadn't wired to any consumer until this addition (it was instead borrowing companion's node.region.scope/default_scope_key as a stand-in -- see kbase/PROTOCOL_AND_SETTINGS_STORAGE.md). Not covered by GET/SET_PREFS_TLV, same as GET_REGION_HOME; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region default' (get form)
#define BEEBO_CMD_SET_REGION_DEFAULT     32  // payload: region name string bytes (no NUL); empty payload clears the default region. Unlike SET_REGION_HOME, auto-creates the named region (flood-allowed) if it doesn't exist yet, matching CommonCLI's text-CLI 'region default <name>' exactly (CommonCLI.cpp's own handleRegionCmd auto-creates via putRegion there too) rather than SET_REGION_HOME's stricter ERR_CODE_NOT_FOUND -- ERR_CODE_TABLE_FULL if MAX_REGION_ENTRIES is reached and no existing region matches. Auto-persists (region_map.save()) on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region default <name>' (set form)
#define BEEBO_CMD_SET_NEIGHBOR_REMOVE    33  // payload: [len:1][pubkey:len] (len 1-32). Prunes the matching entry from the direct (zero-hop) neighbour table -- RAM-only, not persisted, re-populated as adverts are heard again -- using the same prefix-match convention Beebo::putNeighbour() uses for matching an existing slot (compares over min(len, stored pubkey_len) bytes). ERR_CODE_NOT_FOUND if no neighbour matches. Mirrors CommonCLI's text-CLI 'neighbor.remove <hex>'
#define BEEBO_CMD_GET_FULL_VERSION       34  // reply FULL_VERSION + untruncated FIRMWARE_VERSION bytes (no NUL); the standard DEVICE_INFO frame's ver field is a fixed 20 bytes upstream, too short for beebo's mode-suffixed versions (e.g. "...dbg")
#define BEEBO_CMD_CLEAR_PROFILE          35  // reset the command-latency profiling ring (STATS_TYPE_PROFILE) to empty
#define BEEBO_CMD_GET_PREFS_TLV          36  // payload is [role:1][start_index:1] (start_index optional, defaults to 0) -- role is NODE_ROLE_COMPANION=0/NODE_ROLE_REPEATER=1/NODE_ROLE_LIVE, resolved via resolveRoleByte(); start_index is the PREFS_TLV_FIELDS table index to resume from. Reply is RESP_CODE_BEEBO/PREFS_TLV + [next_index:1] + TLV triplets [key:1][len:1][value:len] for every field starting at start_index that fit in this transport's send cap; next_index is 0xFF if this page reached the end of the table, else the index to request next (paginated, same shape as GET_MONRING/GET_NEIGHBORS -- keep calling with the returned next_index until 0xFF). Needed because PREFS_TLV_FIELDS has grown past what a single BLE-capped (176B) frame can hold; WiFi/USB's larger send cap (BULK_XFER) means they get the whole table in one page in practice. This is the only way to read/write any PREFS_TLV_FIELDS field -- there are no separate single-field GET/SET opcodes for them, even when a single field is all a caller wants. multi_role only
#define BEEBO_CMD_SET_PREFS_TLV          37  // payload is [role:1] (or NODE_ROLE_LIVE) followed by one or more [key:1][len:1][value:len] triplets to change -- only the fields being written need to be sent (unlike GET_PREFS_TLV's full dump); one flash write covers every triplet in the payload for that role, however many. Writing PREFS_TLV_TRANSPORT_CONFIG or PREFS_TLV_WIFI_SSID/PREFS_TLV_WIFI_PWD live-applies immediately when the resolved role is also the currently-live role (no reboot needed); use REBOOT_WITH_TIME afterward for the one case that still needs a reboot to apply (usb transport on repeater role). multi_role only
#define BEEBO_CMD_GET_TUNE_ENABLED       38  // reply OK + value (1B) = dynamic-tuning optimizer on/off (RAM-only, see DYNAMIC_OPTIMIZER_PLAN.md; always 0 after reboot); multi_role only
#define BEEBO_CMD_SET_TUNE_ENABLED       39  // payload: 1B value (0/1); RAM-only -- never calls a NodePrefs/ComPrefs setter regardless of this switch (observe-only Phase A); multi_role only
#define BEEBO_CMD_GET_TUNE_APPLIED_MASK  40  // reply OK + value (1B) = per-param live-actuation bitmask, bit i = TuneController::specFor(i)'s param_id (RAM-only, always 0 after reboot); multi_role only
#define BEEBO_CMD_SET_TUNE_APPLIED_MASK  41  // payload: 1B bitmask; RAM-only. A set bit lets that TUNE_* param's proposals actually be written (see TuneController::Decision/Beebo::applyTuneDecision); 0 (default) keeps every param observe-only; multi_role only
#define BEEBO_CMD_GET_ACK_STATS          42  // reply RESP_CODE_BEEBO/ACK_STATS: ack_success_count (4B u32) + ack_timeout_count (4B u32) + ack_overflow_count (4B u32), lifetime counts of confirmed-delivered/timed-out direct-message sends (BaseChatMesh::getAckSuccessCount/getAckTimeoutCount) plus how many times Beebo::expected_ack_table's ring wrapped onto a still-unresolved slot before it could time out properly -- a real starvation event, not a no-op (Beebo::getAckOverflowCount, DYNAMIC_OPTIMIZER_PLAN.md item 9 -- "TX reception confirmation"); companion only, RAM-only (0 after reboot)
#define BEEBO_CMD_GET_ECHO_COUNT         43  // reply RESP_CODE_BEEBO/ECHO_STATS: echo_success_count (4B u32) + echo_timeout_count (4B u32) + echo_overflow_count (4B u32) + self_tx_direct_count (4B u32) -- lifetime counts of confirmed-heard vs. confirmed-timed-out flood self-transmissions (SimpleMeshTables::getEchoSuccessCount/getEchoTimeoutCount), how many times the echo ring wrapped onto a still-unresolved slot before it reached either verdict (SimpleMeshTables::getEchoOverflowCount), plus how many self-transmissions were direct-routed and therefore structurally excluded from ECHO tracking entirely -- a direct/addressed packet can't come back as a flood echo (SimpleMeshTables::getSelfTxDirectCount, DYNAMIC_OPTIMIZER_PLAN.md item 9); RAM-only (0 after reboot)
#define BEEBO_CMD_NODE_DISCOVER          44  // actively query nearby nodes for their identity, rather than waiting on their next periodic self-advert (CTL_TYPE_NODE_DISCOVER_REQ/RESP, see Beebo::sendNodeDiscoverReq()). payload: [filter:1][prefix_only:1]; filter is a bitmask of (1 << ADV_TYPE_*) -- e.g. (1<<ADV_TYPE_REPEATER)|(1<<ADV_TYPE_SENSOR) to ask for repeaters and sensors -- ERR_CODE_ILLEGAL_ARG if 0; prefix_only=1 asks responders to reply with only an 8-byte pubkey prefix instead of the full 32 bytes. Replies OK immediately (the request is a zero-hop broadcast, sent and forgotten); matching CTL_TYPE_NODE_DISCOVER_RESP replies trickle in over the following ~60s and are logged into the existing direct (zero-hop) neighbour table (Beebo::putNeighbour()), same as GET_NEIGHBORS already streams -- poll that command after a short wait to see results. Not role-gated: any role can ask 'who's near me'; only nodes whose own current type matches a set filter bit answer (CTL_TYPE_NODE_DISCOVER_REQ handling in onControlDataRecv(), also not role-gated -- a companion node answers as ADV_TYPE_CHAT, a repeater as ADV_TYPE_REPEATER). Mirrors CommonCLI's text-CLI 'discover.neighbors [repeater|chat|room|sensor|all ...]'
#define BEEBO_CMD_GET_ADVERT_PATHS       45  // stream the WHOLE advert_paths[] cache (ADVERT_PATH_TABLE_SIZE=16 entries, LRU by recv_timestamp) in one round trip, no payload -- the bulk counterpart to upstream's single-pubkey CMD_GET_ADVERT_PATH (0x2a). Match each entry's pubkey_prefix locally against however many contacts the caller cares about instead of issuing one CMD_GET_ADVERT_PATH per contact: the cache only ever holds 16 entries total regardless of contact-list size, so a per-contact loop is always doing 16 real answers' worth of work spread over however many round trips there are contacts, for no benefit over one bulk read. Same START/entry/END streaming shape as GET_NEIGHBORS
#define BEEBO_CMD_GET_PUBLIC_KEY         46  // payload: 1 byte role (NODE_ROLE_COMPANION=0/NODE_ROLE_REPEATER=1); reply RESP_CODE_BEEBO/PUBLIC_KEY with that role's own 32-byte Ed25519 public key, regardless of which role is currently live (PER_ROLE_IDENTITY plan) -- self_info only ever reflects the live role's identity, so companion.public_key/repeater.public_key settings leaves read through this instead. ERR_CODE_ILLEGAL_ARG if role isn't 0/1; ERR_CODE_NOT_FOUND if that role has never been switched into on this device yet (its identity file doesn't exist) -- a GET must never have the side effect of creating one
#define BEEBO_CMD_GET_BOARD_ID           47  // no payload; reply RESP_CODE_BEEBO/BOARD_ID with the ESP32's 6-byte factory eFuse base MAC (esp_efuse_mac_get_default()) -- a hardware-burned identifier, stable across reflashes/identity changes/role switches, independent of node.public_key (ed25519, unrelated to the MAC) and of node.role (shared across both). Not a wire MAC address (no per-interface offset applied, see esp_read_mac()), just a unique per-board ID
#define BEEBO_CMD_UNLOCK_ROLE_SECRETS    48  // payload: [candidate password bytes, up to 15, no NUL] -- checked against BeeboBoardPrefs.board_password (see GET_PREFS_TLV(KEY_OWNER_PASSWORD)), the node's single role-agnostic backup credential, present on every build regardless of which role(s) are compiled in. A mismatch AND an unset (empty) owner_password both fail closed -- unlocking is never possible until the owner has explicitly set this password at least once. Password-gated secret readback for `beebo config backup` (see kbase/PROTOCOL_AND_SETTINGS_STORAGE.md): proves the caller already knows the owner password rather than exposing anything to a bare-reachable, unauthenticated session (multi_role's WiFi/TCP companion transport has no other authentication at all, unlike BLE's paired PIN or USB's physical possession -- this keeps a WiFi-only attacker from harvesting secrets they don't already know). On match, replies RESP_CODE_BEEBO/ROLE_SECRETS with repeater.guest.password + NUL + node.wifi.password + NUL + repeater.password, always in that order (any may be empty; the two repeater-only fields are always empty on a BEEBO_ENABLE_REPEATER_ROLE=0 build, which has no ComPrefs at all) -- one verified owner password unlocks every secret on the device, no separate proof needed per secret, since a session that already knows the owner password already has unrestricted write access to all of them (a companion session can already overwrite any of them blind, with no gate at all) -- reading their current values back is a strictly smaller exposure than that existing write access. A plain EventType.ERROR reply (not a distinct error code -- deliberately indistinguishable from a malformed request) on a mismatched/unset candidate, so a failed guess doesn't confirm anything about the real password's shape/length beyond what a normal login attempt already would. Available on every build, static or dynamic -- no ERR_CODE_UNSUPPORTED_CMD case anymore
#define BEEBO_CMD_GENERATE_IDENTITY      49  // payload: 1 byte role (NODE_ROLE_COMPANION=0/NODE_ROLE_REPEATER=1); generate a fresh random Ed25519 identity for that role on-device, overwriting whatever identity (if any) that role already has -- reuses the exact random-generation + reserved-pubkey-hash-prefix retry loop loadIdentityForRole() already runs on first boot, just independently callable against a role whose identity file may already exist, instead of only ever firing on a missing file. Reply RESP_CODE_BEEBO/PUBLIC_KEY with the new 32-byte Ed25519 public key (same reply shape GET_PUBLIC_KEY uses). If role is currently live, mirrors into role_state_store[role].identity/self_id immediately (same pattern as CMD_IMPORT_PRIVATE_KEY's role==_board.role branch) -- contacts/ACL shared secrets invalidated and reloaded the same way IMPORT already does, since a new keypair invalidates ECDH shared secrets exactly like an imported one does. ERR_CODE_ILLEGAL_ARG if role isn't 0/1. Irreversible -- the prior identity for that role is not retained anywhere; callers that want to keep it should EXPORT_PRIVATE_KEY first
#define BEEBO_CMD_SET_NODE               50  // payload: [role:1][name_len:1][name:name_len][privkey:64] -- atomic import + name-set + role-switch-if-needed + reboot in one server-side call (IDENTITY_SWITCH plan), avoiding the partial-failure window of composing CMD_IMPORT_PRIVATE_KEY + SET_PREFS_TLV(KEY_NAME) + SET_NODE_ROLE as separate client-driven round trips (e.g. the keypair import succeeding but a later name-set/role-switch call failing or the connection dropping mid-sequence). role must be NODE_ROLE_COMPANION/NODE_ROLE_REPEATER and built into this binary; name_len may be 0 to leave that role's name untouched, else the bytes are written the same way SET_PREFS_TLV(KEY_NAME) would (silently truncated to fit, never rejected for length). privkey is validated exactly like CMD_IMPORT_PRIVATE_KEY's own (ERR_CODE_ILLEGAL_ARG if invalid). Refused with ERR_CODE_BAD_STATE if an OTA or bulk-transfer session is in progress, checked BEFORE any write so a busy device is left completely untouched. Switches board.node.role to the target role if it differs (same requestNodeRoleSwitch() persistence any other role switch uses) and unconditionally reboots afterward, whether or not the role actually changed -- the reboot is what makes the new identity/name authoritative on reload, not any in-place mirroring. No reply -- the device restarts immediately, same as REBOOT_WITH_TIME
#define BEEBO_CMD_DEBUG_LOG_ENABLE       51  // payload: [on:1] -- enables (1) or disables (0) the live debug-event push, always over USB regardless of which transport (if any) holds the companion session: while enabled, every DLOGH/M/L(...) call anywhere in the firmware pushes an unsolicited RESP_CODE_BEEBO/DEBUG_LOG frame (DebugRing.h's global debug_ring singleton, DebugRing::logLink()) directly over usb_interface, and every RLOGH/M/L(...) call also pushes a RESP_CODE_BEEBO/DEBUG_TLOG frame (DebugRing::logRing()) the same way -- both no-ops while disabled, or while USB has nothing connected on the far end. RLOGH/M also records into the in-RAM debug ring (STATS_TYPE_TRANSPORT, fetched via GET_STATS) regardless of whether the live link is enabled; RLOGL (Low severity) and every DLOGH/M/L never do -- L is link-only, same as DLOGH/M/L, and the ring only ever holds fixed-size structured H/M records. Only H severity is compiled in by default -- M/L call sites compile to nothing unless the build defines DEBUG_LOG_VERBOSE=1. Not tied to any one session's lifetime -- stays enabled across BLE/TCP session churn and USB cable replug until explicitly disabled or the device reboots. Every disabled -> enabled transition (not just the first one since boot) replays the ring's current backlog before any new live event, so a fresh `-d`/`-i` connection always sees recent history, not just events from the moment it happened to attach; a same-connection resend of an already-enabled state (e.g. a lost-first-byte retry) triggers no second replay. Replies ERR_CODE_BAD_STATE instead of OK if USB transport isn't up on this build (board.usb_enabled=0), since there is nowhere for the enabled stream to go. `beebo --debug` is the CLI counterpart -- see kbase/DEBUGGING.md

// beebo response sub-ids (payload byte 0 after RESP_CODE_BEEBO)
#define BEEBO_RESP_OTA_BEGIN             1  // response to OTA_BEGIN
#define BEEBO_RESP_NEIGHBORS_START       2  // first reply to GET_NEIGHBORS: count + node time
#define BEEBO_RESP_NEIGHBOR              3  // one per direct neighbour
#define BEEBO_RESP_END_OF_NEIGHBORS      4  // last reply to GET_NEIGHBORS
#define BEEBO_RESP_MONRING               5  // reply to GET_MONRING: status header + records. Header's trailing reset:1 byte is 1 if the request's after_seq was overridden (after_ts predated the ring's current oldest resident record) and the reply starts from the oldest record instead, 0 if honored as given
#define BEEBO_RESP_XFER_CAPS             6  // (BULK_XFER): reply to SET_XFER_CAPS: granted [max_tx:2 LE][stream:1]
#define BEEBO_RESP_FULL_VERSION          7  // reply to GET_FULL_VERSION: untruncated FIRMWARE_VERSION bytes (no NUL)
#define BEEBO_RESP_PREFS_TLV             8  // reply to GET_PREFS_TLV: TLV triplets, see that command's desc
#define BEEBO_RESP_ACK_STATS             9  // reply to GET_ACK_STATS: ack_success_count (4B u32 LE) + ack_timeout_count (4B u32 LE) + ack_overflow_count (4B u32 LE)
#define BEEBO_RESP_ECHO_STATS           10  // reply to GET_ECHO_COUNT: echo_success_count (4B u32 LE) + echo_timeout_count (4B u32 LE) + echo_overflow_count (4B u32 LE) + self_tx_direct_count (4B u32 LE)
#define BEEBO_RESP_REGION_HOME          11  // reply to GET_REGION_HOME: home region name bytes (no NUL, may be empty)
#define BEEBO_RESP_REGION_LIST          12  // reply to GET_REGION_LIST: comma-separated region name bytes (no NUL, may be empty)
#define BEEBO_RESP_REGION_TREE          13  // reply to GET_REGION_TREE: RegionMap::exportTo()'s hierarchical text export bytes (no NUL, may be empty)
#define BEEBO_RESP_ADVERT_PATHS_START   14  // first reply to GET_ADVERT_PATHS: count of populated advert_paths[] entries (4B LE)
#define BEEBO_RESP_ADVERT_PATH          15  // one per populated advert_paths[] entry: pubkey_prefix (7B) + name (32B, no NUL) + recv_timestamp (4B LE) + path_len (1B) + path (Packet::writePath-encoded, variable length per path_len)
#define BEEBO_RESP_END_OF_ADVERT_PATHS  16  // last reply to GET_ADVERT_PATHS
#define BEEBO_RESP_PUBLIC_KEY           17  // reply to GET_PUBLIC_KEY: that role's 32-byte Ed25519 public key
#define BEEBO_RESP_BOARD_ID             18  // reply to GET_BOARD_ID: 6-byte eFuse base MAC
#define BEEBO_RESP_ROLE_SECRETS         19  // reply to UNLOCK_ROLE_SECRETS on a matching candidate: repeater.guest.password + NUL + node.wifi.password + NUL + repeater.password (any may be empty)
#define BEEBO_RESP_REGION_DEFAULT       20  // reply to GET_REGION_DEFAULT: default-region name bytes (no NUL, may be empty)
#define BEEBO_RESP_DEBUG_LOG            21  // unsolicited push over USB while DEBUG_LOG_ENABLE is on (never a reply to a specific request), from a DLOGH/M/L(id, fmt, ...) call site: [millis:4 LE][id:2 LE][severity:1][line:2 LE][file_len:1][file: basename, no NUL][text: message, no NUL, truncated to fit this transport's send cap]. id is hand-picked by the caller (reusing the same id at two call sites means 'this is the same logical event'); severity is 0=H/1=M/2=L. See DEBUG_LOG_ENABLE's own desc
#define BEEBO_RESP_DEBUG_TLOG           22  // unsolicited push over USB while DEBUG_LOG_ENABLE is on, one per RLOGH/M/L(type, detail) call as it's recorded (DebugRing::logRing(), which also appends it to the in-RAM ring unless severity is Low) -- [millis:4 LE][id:2 LE][severity:1][line:2 LE][file_len:1][file: basename, no NUL][detail:4 LE]. id is the same value as the ring's own `type` (RLOG_ID_* in DebugRing.h) -- already a hand-picked, sometimes-reused-on-purpose per-call-site tag. Decode with the same RLOG_NAMES/_detail_str() table `beebo monitor transport` uses. See DEBUG_LOG_ENABLE's own desc
