#pragma once

// GENERATED FILE -- do not hand-edit. Source: protocol.yaml. Regenerate with `python tools/gen_protocol.py`.

// The only two upstream CMD/RESP slots beebo claims -- every beebo
// action is a flat u8 sub-id carried as the first payload byte after
// one of these.
#define CMD_BEEBO        222
#define RESP_CODE_BEEBO  223

// beebo command sub-ids (payload byte 0 after CMD_BEEBO)
#define BEEBO_CMD_OTA_BEGIN                 128  // start OTA session
#define BEEBO_CMD_OTA_WRITE                 129  // write firmware chunk
#define BEEBO_CMD_OTA_END                   130  // finalize and reboot. payload (optional): 4B LE uint32 epoch seconds, the caller's own current clock -- if present, used for the deferred restart's NVS persistence and live clock correction instead of this device's own current time (see REBOOT_WITH_TIME's own desc for why); omit for the old behavior
#define BEEBO_CMD_GET_SAVE_PREFS            134  // reply OK + value (byte0 = save_prefs, 1=on)
#define BEEBO_CMD_SET_SAVE_PREFS            135  // payload: 1 byte -- 0=off, 1=on, 2=restore(reload), 3=commit(write now)
#define BEEBO_CMD_SET_CW                    136  // bench CW carrier. payload: [on:1][max_secs:2 LE]; on=0 stops
#define BEEBO_CMD_SET_TX_OPTIMIZE           137  // PA optimization. payload: [on:1]; 1=paOptTable(default), 0=fixed/monotonic
#define BEEBO_CMD_GET_NEIGHBORS             138  // stream the direct (zero-hop) neighbour table
#define BEEBO_CMD_GET_MONRING               139  // read monitor ring. payload: [after_seq:4 LE] (optional) [after_ts:4 LE] (optional, capture-time epoch of the record at after_seq as the client last recorded it -- lets the firmware detect a reboot/clear/wraparound since then and override to a full read, since after_seq alone can alias across MonRing::_next_seq resetting to 0; see the reply's reset flag)
#define BEEBO_CMD_SET_MONRING               140  // control RX capture. payload: [op:1] 0=pause 1=resume 2=clear 3=set config (byte2, persisted)
#define BEEBO_CMD_SET_XFER_CAPS             141  // (BULK_XFER): negotiate bulk-transfer caps. payload: [max_rx_frame:2 LE][flags:1]; flags bit0=accept streamed reads
#define BEEBO_CMD_APP_DISCONNECT            146  // disconnect the companion session
#define BEEBO_CMD_SEND_POKE                 152  // originate a 'poke' to a contact. payload: [pub_key:PUB_KEY_SIZE]
#define BEEBO_CMD_GET_BATT_STATE            153  // reply OK + value (4B LE) = BATT_STATE_* (byte0); RAM-only live sensor state, not a PrefsTlv field
#define BEEBO_CMD_GET_QUIET                 160  // reply OK + value (1B) = bench-quiet state (0=off, 1=on)
#define BEEBO_CMD_SET_QUIET                 161  // payload: 1B value (0=off -> reboots, 1=on -> sleeps radio+FEM); RAM-only, not persisted
#define BEEBO_CMD_SET_BATT_STATE            166  // payload: 1B value = BATT_STATE_*; RAM-only, not persisted; re-seeds the trend anchor
#define BEEBO_CMD_GET_NODE_ROLE             169  // reply OK + value (4B LE) = NODE_ROLE_* (0=companion, 1=repeater); multi_role only
#define BEEBO_CMD_SET_NODE_ROLE             170  // payload: 1B value = NODE_ROLE_*; persisted; hot switch (immediate); multi_role only
#define BEEBO_CMD_SET_REPEATER_PASSWORD     197  // payload: password string bytes (no NUL, up to 15); write-only, updates RAM + ComPrefs; multi_role only
#define BEEBO_CMD_SET_GUEST_PASSWORD        198  // payload: password string bytes (no NUL, up to 15); write-only, updates RAM + ComPrefs; multi_role only
#define BEEBO_CMD_GET_REPEATER_PASSWORD_SET 228  // reply OK + value (4B LE) = 1 if repeater.password differs from the firmware's built-in default ("password"), 0 if it's still the default -- same is-it-set-boolean shape as GET_PREFS_TLV's wifi_pwd field, but compares against the known default server-side rather than just checking non-empty (the password is never empty by construction, it always has a value); never the password itself; multi_role only
#define BEEBO_CMD_REBOOT_WITH_TIME          229  // payload: 4B LE uint32 epoch seconds (the caller's own current clock); same as the plain reboot command, but uses this timestamp instead of the device's own current time for both the NVS RTC backup (see ESP32Board.h's beebo_persistRTCTimeForReboot()/rebootWithTime()) and a live clock correction applied immediately before restarting -- for a device whose live clock is itself wrong, where every ordinary reboot just re-persists (and never corrects) the same bad value. The live-clock correction is safe specifically because it's immediately followed by esp_restart() with nothing else running in between -- no in-flight timer/deadline logic ever observes the jump. No reply -- the device restarts immediately, same as the plain reboot command
#define BEEBO_CMD_GET_REGION_HOME           230  // reply REGION_HOME + home region name bytes (no NUL, may be 0 bytes if no home region is set); RegionMap-backed (src/helpers/RegionMap.h), not a ComPrefs/NodePrefs field -- separate persistence (region_map.save()), not covered by GET/SET_PREFS_TLV; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region home' (get form)
#define BEEBO_CMD_SET_REGION_HOME           231  // payload: region name string bytes (no NUL); empty payload clears the home region; '*' (RegionMap's built-in wildcard/catch-all entry) is rejected -- setting home to it can never be read back correctly (getHomeRegion() doesn't resolve it). The name must already exist (define one first with SET_REGION_PUT or a RepeaterLink's text-CLI 'region put <name>') or ERR_CODE_NOT_FOUND is returned; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region home <name>' (set form)
#define BEEBO_CMD_GET_REGION_LIST           232  // reply REGION_LIST + comma-separated region names (no NUL), via RegionMap::exportNamesTo() with no flood-allow/deny filtering (every defined region, not just flood-allowed ones) -- flat names only, no parent/hierarchy or flood-flag info; see GET_REGION_TREE for that. Read-only; multi_role only, repeater role
#define BEEBO_CMD_GET_REGION_TREE           233  // reply REGION_TREE + RegionMap::exportTo()'s full hierarchical text export (no NUL): one line per region, indented by tree depth, each line '<name>[^][ F]' where ^ marks the home region and a trailing ' F' marks flood-allowed (absence means flood-denied) -- same format/content as CommonCLI's text-CLI bare 'region' command. Read-only; multi_role only, repeater role
#define BEEBO_CMD_SET_REGION_PUT            234  // payload: name\0parent\0 (name required; parent optional -- empty or omitted means the wildcard root, matching CommonCLI's 'region put <name> [parent]' default). Creates the region if it doesn't exist (flood-allowed by default, matching CommonCLI's own post-put reset) or re-parents it if it does; ERR_CODE_NOT_FOUND if a non-empty parent name doesn't exist, ERR_CODE_TABLE_FULL if MAX_REGION_ENTRIES is reached. Auto-persists (region_map.save()) on success, unlike CommonCLI's text-CLI which needs an explicit 'region save' after 'region put'; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region put'
#define BEEBO_CMD_SET_REGION_REMOVE         235  // payload: region name string bytes (no NUL). ERR_CODE_NOT_FOUND if it doesn't exist; ERR_CODE_ILLEGAL_ARG if it still has child regions (RegionMap::removeRegion() refuses to remove a non-empty parent -- remove or re-parent its children first). Auto-persists on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region remove'
#define BEEBO_CMD_SET_REGION_ALLOWF         236  // payload: region name string bytes (no NUL); clears that region's REGION_DENY_FLOOD flag (flood-allowed). ERR_CODE_NOT_FOUND if it doesn't exist. Auto-persists on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region allowf'
#define BEEBO_CMD_SET_REGION_DENYF          237  // payload: region name string bytes (no NUL); sets that region's REGION_DENY_FLOOD flag (flood-denied). ERR_CODE_NOT_FOUND if it doesn't exist. Auto-persists on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region denyf'
#define BEEBO_CMD_SET_REGION_DEF            241  // payload: def string bytes (no NUL), same space-separated multi-segment DSL as CommonCLI's text-CLI 'region def <segments>': each segment is 'name' or 'name|jump'/'name,jump' (define 'name' under the current cursor -- wildcard root at the start -- then move the cursor to 'jump', an existing region found by name-prefix match, or stay at the newly-defined 'name' if no jump is given). Lets one command build a whole subtree instead of N 'region put' round trips. Each new region is flood-allowed by default (same as SET_REGION_PUT). ERR_CODE_ILLEGAL_ARG on an empty name or empty jump target, ERR_CODE_NOT_FOUND on an unresolvable jump target, ERR_CODE_TABLE_FULL if MAX_REGION_ENTRIES is reached -- the whole def is applied segment-by-segment and stops at the first error (already-applied segments before it are NOT rolled back, matching CommonCLI's own 'region def' behavior). Auto-persists (region_map.save()) on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region def'
#define BEEBO_CMD_SET_REGION_SAVE           242  // no payload; explicitly persists region_map to flash (region_map.save()). Every other SET_REGION_* opcode already auto-persists on success, so this is a no-op in practice for binary-mode devices -- it exists purely for backward compatibility with CommonCLI's text-CLI 'region save', which callers may still send out of habit after a 'region put'/'region def'. Replies OK on success, ERR_CODE_FILE_IO_ERROR if the flash write itself failed (mirrors CommonCLI's text-CLI 'region save' surfacing its own saveRegions() callback's result). multi_role only, repeater role
#define BEEBO_CMD_GET_REGION_DEFAULT        205  // reply REGION_DEFAULT + default-region name bytes (no NUL, may be 0 bytes if no default region is set); RegionMap's own independent default_id (RegionMap::getDefaultRegion()), distinct from home_id/GET_REGION_HOME -- restores stock simple_repeater's own default-scope mechanism (MyMesh.cpp begin()/onDefaultRegionChanged()), which multi_role's repeater role hadn't wired to any consumer until this addition (it was instead borrowing companion's node.region.scope/default_scope_key as a stand-in -- see kbase/PROTOCOL_AND_SETTINGS_STORAGE.md). Not covered by GET/SET_PREFS_TLV, same as GET_REGION_HOME; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region default' (get form)
#define BEEBO_CMD_SET_REGION_DEFAULT        206  // payload: region name string bytes (no NUL); empty payload clears the default region. Unlike SET_REGION_HOME, auto-creates the named region (flood-allowed) if it doesn't exist yet, matching CommonCLI's text-CLI 'region default <name>' exactly (CommonCLI.cpp's own handleRegionCmd auto-creates via putRegion there too) rather than SET_REGION_HOME's stricter ERR_CODE_NOT_FOUND -- ERR_CODE_TABLE_FULL if MAX_REGION_ENTRIES is reached and no existing region matches. Auto-persists (region_map.save()) on success; multi_role only, repeater role. Mirrors CommonCLI's text-CLI 'region default <name>' (set form)
#define BEEBO_CMD_SET_NEIGHBOR_REMOVE       238  // payload: [len:1][pubkey:len] (len 1-32). Prunes the matching entry from the direct (zero-hop) neighbour table -- RAM-only, not persisted, re-populated as adverts are heard again -- using the same prefix-match convention Beebo::putNeighbour() uses for matching an existing slot (compares over min(len, stored pubkey_len) bytes). ERR_CODE_NOT_FOUND if no neighbour matches. Mirrors CommonCLI's text-CLI 'neighbor.remove <hex>'
#define BEEBO_CMD_GET_FULL_VERSION          199  // reply FULL_VERSION + untruncated FIRMWARE_VERSION bytes (no NUL); the standard DEVICE_INFO frame's ver field is a fixed 20 bytes upstream, too short for beebo's mode-suffixed versions (e.g. "...dbg")
#define BEEBO_CMD_CLEAR_PROFILE             211  // reset the command-latency profiling ring (STATS_TYPE_PROFILE) to empty
#define BEEBO_CMD_GET_PREFS_TLV             212  // payload is [role:1] (NODE_ROLE_COMPANION=0/NODE_ROLE_REPEATER=1/NODE_ROLE_LIVE, resolved via resolveRoleByte()); one round trip for every field in Beebo.h's PREFS_TLV_KEY_* table, scoped to that role, as TLV triplets [key:1][len:1][value:len]; this is the only way to read/write any of those fields -- there are no separate single-field GET/SET opcodes for them, even when a single field is all a caller wants (a one-triplet batch costs the same one round trip). multi_role only
#define BEEBO_CMD_SET_PREFS_TLV             213  // payload is [role:1] (or NODE_ROLE_LIVE) followed by one or more [key:1][len:1][value:len] triplets to change -- only the fields being written need to be sent (unlike GET_PREFS_TLV's full dump); one flash write covers every triplet in the payload for that role, however many. Writing PREFS_TLV_TRANSPORT_CONFIG or PREFS_TLV_WIFI_SSID/PREFS_TLV_WIFI_PWD live-applies immediately when the resolved role is also the currently-live role (no reboot needed); use REBOOT_WITH_TIME afterward for the one case that still needs a reboot to apply (usb transport on repeater role). multi_role only
#define BEEBO_CMD_GET_TUNE_ENABLED          214  // reply OK + value (1B) = dynamic-tuning optimizer on/off (RAM-only, see DYNAMIC_OPTIMIZER_PLAN.md; always 0 after reboot); multi_role only
#define BEEBO_CMD_SET_TUNE_ENABLED          215  // payload: 1B value (0/1); RAM-only -- never calls a NodePrefs/ComPrefs setter regardless of this switch (observe-only Phase A); multi_role only
#define BEEBO_CMD_GET_TUNE_APPLIED_MASK     216  // reply OK + value (1B) = per-param live-actuation bitmask, bit i = TuneController::specFor(i)'s param_id (RAM-only, always 0 after reboot); multi_role only
#define BEEBO_CMD_SET_TUNE_APPLIED_MASK     217  // payload: 1B bitmask; RAM-only. A set bit lets that TUNE_* param's proposals actually be written (see TuneController::Decision/Beebo::applyTuneDecision); 0 (default) keeps every param observe-only; multi_role only
#define BEEBO_CMD_GET_ACK_STATS             222  // reply RESP_CODE_BEEBO/ACK_STATS: ack_success_count (4B u32) + ack_timeout_count (4B u32) + ack_overflow_count (4B u32), lifetime counts of confirmed-delivered/timed-out direct-message sends (BaseChatMesh::getAckSuccessCount/getAckTimeoutCount) plus how many times Beebo::expected_ack_table's ring wrapped onto a still-unresolved slot before it could time out properly -- a real starvation event, not a no-op (Beebo::getAckOverflowCount, DYNAMIC_OPTIMIZER_PLAN.md item 9 -- "TX reception confirmation"); companion only, RAM-only (0 after reboot)
#define BEEBO_CMD_GET_ECHO_COUNT            223  // reply RESP_CODE_BEEBO/ECHO_STATS: echo_success_count (4B u32) + echo_timeout_count (4B u32) + echo_overflow_count (4B u32) + self_tx_direct_count (4B u32) -- lifetime counts of confirmed-heard vs. confirmed-timed-out flood self-transmissions (SimpleMeshTables::getEchoSuccessCount/getEchoTimeoutCount), how many times the echo ring wrapped onto a still-unresolved slot before it reached either verdict (SimpleMeshTables::getEchoOverflowCount), plus how many self-transmissions were direct-routed and therefore structurally excluded from ECHO tracking entirely -- a direct/addressed packet can't come back as a flood echo (SimpleMeshTables::getSelfTxDirectCount, DYNAMIC_OPTIMIZER_PLAN.md item 9); RAM-only (0 after reboot)
#define BEEBO_CMD_GET_DEDUP_WINDOW          224  // reply OK + value (4B LE) = milliseconds [0 to 60000]; 0 is a real, literal value -- disables live-eviction counting entirely (see SimpleMeshTables::hasSeen(), millis()-resolution, not RTC-second), not a default sentinel -- companion value; the dedup-table eviction count itself is already in GET_MONRING's header (rx_dedup_table_full_count, gated to only count evictions still within this window); see GET_REPEATER_DEDUP_WINDOW for the independent repeater copy
#define BEEBO_CMD_SET_DEDUP_WINDOW          225  // payload: 4B LE uint32 milliseconds [0 to 60000]; 0 disables live-eviction counting entirely; out-of-range rejected (ERR_CODE_ILLEGAL_ARG); persisted; companion value -- see SET_REPEATER_DEDUP_WINDOW for the independent repeater copy
#define BEEBO_CMD_GET_MONRING_EVENT_MASK    239  // reply OK + value (4B LE) = per-event-type MON_EVENT capture bitmask, bit N = MonRing.h's EVENT_* id N; 1=captured. RAM-only (all-1s/capture-everything after reboot), independent of the per-kind monring_config MON_CAP_EVENT bit (that bit gates MON_EVENT capture at all; this mask further filters which event TYPES within it are kept -- capture is expensive per DYNAMIC_OPTIMIZER_PLAN.md, most event types are low-volume faults worth always keeping, a few (e.g. tx_ack_success/tx_echo_success) can be high-volume on a busy node and worth excluding without losing the rest)
#define BEEBO_CMD_SET_MONRING_EVENT_MASK    240  // payload: 4B LE uint32 bitmask, same encoding as GET_MONRING_EVENT_MASK; RAM-only, not persisted
#define BEEBO_CMD_NODE_DISCOVER             243  // actively query nearby nodes for their identity, rather than waiting on their next periodic self-advert (CTL_TYPE_NODE_DISCOVER_REQ/RESP, see Beebo::sendNodeDiscoverReq()). payload: [filter:1][prefix_only:1]; filter is a bitmask of (1 << ADV_TYPE_*) -- e.g. (1<<ADV_TYPE_REPEATER)|(1<<ADV_TYPE_SENSOR) to ask for repeaters and sensors -- ERR_CODE_ILLEGAL_ARG if 0; prefix_only=1 asks responders to reply with only an 8-byte pubkey prefix instead of the full 32 bytes. Replies OK immediately (the request is a zero-hop broadcast, sent and forgotten); matching CTL_TYPE_NODE_DISCOVER_RESP replies trickle in over the following ~60s and are logged into the existing direct (zero-hop) neighbour table (Beebo::putNeighbour()), same as GET_NEIGHBORS already streams -- poll that command after a short wait to see results. Not role-gated: any role can ask 'who's near me'; only nodes whose own current type matches a set filter bit answer (CTL_TYPE_NODE_DISCOVER_REQ handling in onControlDataRecv(), also not role-gated -- a companion node answers as ADV_TYPE_CHAT, a repeater as ADV_TYPE_REPEATER). Mirrors CommonCLI's text-CLI 'discover.neighbors [repeater|chat|room|sensor|all ...]'
#define BEEBO_CMD_GET_ADVERT_PATHS          244  // stream the WHOLE advert_paths[] cache (ADVERT_PATH_TABLE_SIZE=16 entries, LRU by recv_timestamp) in one round trip, no payload -- the bulk counterpart to upstream's single-pubkey CMD_GET_ADVERT_PATH (0x2a). Match each entry's pubkey_prefix locally against however many contacts the caller cares about instead of issuing one CMD_GET_ADVERT_PATH per contact: the cache only ever holds 16 entries total regardless of contact-list size, so a per-contact loop is always doing 16 real answers' worth of work spread over however many round trips there are contacts, for no benefit over one bulk read. Same START/entry/END streaming shape as GET_NEIGHBORS
#define BEEBO_CMD_GET_PUBLIC_KEY            245  // payload: 1 byte role (NODE_ROLE_COMPANION=0/NODE_ROLE_REPEATER=1); reply RESP_CODE_BEEBO/PUBLIC_KEY with that role's own 32-byte Ed25519 public key, regardless of which role is currently live (PER_ROLE_IDENTITY plan) -- self_info only ever reflects the live role's identity, so companion.public_key/repeater.public_key settings leaves read through this instead. ERR_CODE_ILLEGAL_ARG if role isn't 0/1; ERR_CODE_NOT_FOUND if that role has never been switched into on this device yet (its identity file doesn't exist) -- a GET must never have the side effect of creating one
#define BEEBO_CMD_GET_BOARD_ID              246  // no payload; reply RESP_CODE_BEEBO/BOARD_ID with the ESP32's 6-byte factory eFuse base MAC (esp_efuse_mac_get_default()) -- a hardware-burned identifier, stable across reflashes/identity changes/role switches, independent of node.public_key (ed25519, unrelated to the MAC) and of node.role (shared across both). Not a wire MAC address (no per-interface offset applied, see esp_read_mac()), just a unique per-board ID
#define BEEBO_CMD_GET_BOARD_NAME            251  // no payload; reply RESP_CODE_BEEBO/BOARD_NAME with BeeboCompanionPrefs.board_name bytes (no NUL, may be empty). Human-editable alias for this physical board's identity (board.id, the read-only eFuse MAC) -- distinct from the per-role persona names (companion.name/repeater.name, see GET_ROLE_NAME): board.name identifies the hardware, not a role. Role-agnostic -- BeeboCompanionPrefs is compiled into every build (multi_role, static companion, static repeater), same as owner_password. Empty until the operator sets one (see beebo/plans/DEVICE_NAME.md); `beebo config`'s default filenames fall back to board.id's hex string until then
#define BEEBO_CMD_SET_BOARD_NAME            252  // payload: name string bytes (no NUL, up to 31); updates RAM + BeeboCompanionPrefs.board_name. Purely a local label -- unlike node.owner.password this has no gating/security role, it's just a friendlier name than board.id's raw hex for a human to recognize the device by
#define BEEBO_CMD_SET_OWNER_PASSWORD        248  // payload: password string bytes (no NUL, up to 15); write-only, updates RAM + BeeboCompanionPrefs.owner_password. Role-agnostic -- BeeboCompanionPrefs is compiled into every build (multi_role, static companion, static repeater), unlike ComPrefs/repeater.password which only exists when BEEBO_ENABLE_REPEATER_ROLE=1. This is the node's one backup/recovery credential (see UNLOCK_ROLE_SECRETS below), distinct from repeater.password (mesh admin login, only meaningful when the repeater role is actually compiled in)
#define BEEBO_CMD_GET_OWNER_PASSWORD_SET    249  // reply OK + value (4B LE) = 1 if node.owner.password has ever been set (non-empty), 0 if still unset -- unlike repeater.password there's no compiled-in default to compare against (empty is the only unset state); never the password itself
#define BEEBO_CMD_GET_ROLE_NAME             250  // payload: 1 byte role (NODE_ROLE_COMPANION=0/NODE_ROLE_REPEATER=1); reply RESP_CODE_BEEBO/ROLE_NAME with that role's own name, regardless of which role is currently live -- reads that role's own resident role_state_store[] slot directly (never the live role's slot), mirrors GET_PUBLIC_KEY. NODE_ROLE_COMPANION replies NodePrefs.node_name; NODE_ROLE_REPEATER replies ComPrefs.node_name; empty if that role's name was never set, no fallback between roles. companion.name/repeater.name settings leaves and anything else that needs a role's own name irrespective of what's live (`beebo config pull/diff/push --role`, ...) read through here -- RESP_CODE_SELF_INFO's own "name" field is live-role-scoped (swaps with type/pubkey per GET_NODE_ROLE's hot-switch, see that reply's own comment), so it's only correct for whichever role is actually live, not an arbitrary target role. Always succeeds for either role (unlike GET_PUBLIC_KEY, a name isn't gated on that role's identity having ever been created). ERR_CODE_ILLEGAL_ARG if role isn't 0/1
#define BEEBO_CMD_UNLOCK_ROLE_SECRETS       247  // payload: [candidate password bytes, up to 15, no NUL] -- checked against BeeboCompanionPrefs.owner_password (see SET_OWNER_PASSWORD), the node's single role-agnostic backup credential, present on every build regardless of which role(s) are compiled in. A mismatch AND an unset (empty) owner_password both fail closed -- unlocking is never possible until the owner has explicitly set this password at least once. Password-gated secret readback for `beebo config backup` (see beebo/plans/SETTINGS_ISOLATION.md): proves the caller already knows the owner password rather than exposing anything to a bare-reachable, unauthenticated session (multi_role's WiFi/TCP companion transport has no other authentication at all, unlike BLE's paired PIN or USB's physical possession -- this keeps a WiFi-only attacker from harvesting secrets they don't already know). On match, replies RESP_CODE_BEEBO/ROLE_SECRETS with repeater.guest.password + NUL + node.wifi.password + NUL + repeater.password, always in that order (any may be empty; the two repeater-only fields are always empty on a BEEBO_ENABLE_REPEATER_ROLE=0 build, which has no ComPrefs at all) -- one verified owner password unlocks every secret on the device, no separate proof needed per secret, since a session that already knows the owner password already has unrestricted write access to all of them (a companion session can already overwrite any of them blind, with no gate at all) -- reading their current values back is a strictly smaller exposure than that existing write access. A plain EventType.ERROR reply (not a distinct error code -- deliberately indistinguishable from a malformed request) on a mismatched/unset candidate, so a failed guess doesn't confirm anything about the real password's shape/length beyond what a normal login attempt already would. Available on every build, static or dynamic -- no ERR_CODE_UNSUPPORTED_CMD case anymore

// beebo response sub-ids (payload byte 0 after RESP_CODE_BEEBO)
#define BEEBO_RESP_OTA_BEGIN           200  // response to OTA_BEGIN
#define BEEBO_RESP_NEIGHBORS_START     201  // first reply to GET_NEIGHBORS: count + node time
#define BEEBO_RESP_NEIGHBOR            202  // one per direct neighbour
#define BEEBO_RESP_END_OF_NEIGHBORS    203  // last reply to GET_NEIGHBORS
#define BEEBO_RESP_MONRING             204  // reply to GET_MONRING: status header + records. Header's trailing reset:1 byte is 1 if the request's after_seq was overridden (after_ts predated the ring's current oldest resident record) and the reply starts from the oldest record instead, 0 if honored as given
#define BEEBO_RESP_XFER_CAPS           205  // (BULK_XFER): reply to SET_XFER_CAPS: granted [max_tx:2 LE][stream:1]
#define BEEBO_RESP_FULL_VERSION        208  // reply to GET_FULL_VERSION: untruncated FIRMWARE_VERSION bytes (no NUL)
#define BEEBO_RESP_PREFS_TLV           210  // reply to GET_PREFS_TLV: TLV triplets, see that command's desc
#define BEEBO_RESP_ACK_STATS           211  // reply to GET_ACK_STATS: ack_success_count (4B u32 LE) + ack_timeout_count (4B u32 LE) + ack_overflow_count (4B u32 LE)
#define BEEBO_RESP_ECHO_STATS          212  // reply to GET_ECHO_COUNT: echo_success_count (4B u32 LE) + echo_timeout_count (4B u32 LE) + echo_overflow_count (4B u32 LE) + self_tx_direct_count (4B u32 LE)
#define BEEBO_RESP_REGION_HOME         213  // reply to GET_REGION_HOME: home region name bytes (no NUL, may be empty)
#define BEEBO_RESP_REGION_LIST         214  // reply to GET_REGION_LIST: comma-separated region name bytes (no NUL, may be empty)
#define BEEBO_RESP_REGION_TREE         215  // reply to GET_REGION_TREE: RegionMap::exportTo()'s hierarchical text export bytes (no NUL, may be empty)
#define BEEBO_RESP_ADVERT_PATHS_START  216  // first reply to GET_ADVERT_PATHS: count of populated advert_paths[] entries (4B LE)
#define BEEBO_RESP_ADVERT_PATH         217  // one per populated advert_paths[] entry: pubkey_prefix (7B) + name (32B, no NUL) + recv_timestamp (4B LE) + path_len (1B) + path (Packet::writePath-encoded, variable length per path_len)
#define BEEBO_RESP_END_OF_ADVERT_PATHS 218  // last reply to GET_ADVERT_PATHS
#define BEEBO_RESP_PUBLIC_KEY          219  // reply to GET_PUBLIC_KEY: that role's 32-byte Ed25519 public key
#define BEEBO_RESP_BOARD_ID            220  // reply to GET_BOARD_ID: 6-byte eFuse base MAC
#define BEEBO_RESP_ROLE_SECRETS        221  // reply to UNLOCK_ROLE_SECRETS on a matching candidate: repeater.guest.password + NUL + node.wifi.password + NUL + repeater.password (any may be empty)
#define BEEBO_RESP_ROLE_NAME           222  // reply to GET_ROLE_NAME: that role's own name bytes (no NUL)
#define BEEBO_RESP_BOARD_NAME          223  // reply to GET_BOARD_NAME: board.name bytes (no NUL, may be empty)
#define BEEBO_RESP_REGION_DEFAULT      224  // reply to GET_REGION_DEFAULT: default-region name bytes (no NUL, may be empty)
